export type Lang = 'VN' | 'JP';


const vnText = {
  shared: {
    loadingWorkspace: 'Đang tải không gian làm việc',
    userLabel: 'Người dùng',
    statusLabel: 'Trạng thái',
    statusOnline: 'Lab đang hoạt động',
    refresh: 'Làm mới',
    languageLabel: 'Ngôn ngữ',
    languageToggle: 'Chuyển ngôn ngữ',
    languageNames: { VN: 'Tiếng Việt', JP: 'English' },
    themeLabel: 'Giao diện',
    themeToggle: 'Chuyển giao diện',
    themeLight: 'Chế độ sáng',
    themeDark: 'Chế độ tối',
    openNavigation: 'Mở điều hướng',
    closeNavigation: 'Đóng điều hướng',
    closeOverlay: 'Đóng lớp phủ điều hướng',
    backDashboard: 'Quay về tổng quan',
    systemUser: 'Người dùng hệ thống',
    pageUnavailable: 'Trang này đang được hoàn thiện.',
    pageLoadFailed: 'Không thể tải yêu cầu này.',
    jobDetailSelectedNote: 'Kiểm tra yêu cầu {id} cùng toàn bộ ghi chú vận hành liên quan.',
    noDate: 'Chưa có mốc thời gian',
    noDuration: 'Chưa có thời lượng',
    notAssigned: 'Chưa xếp',
    waitingApproval: 'Chờ duyệt',
    createdOn: 'Tạo ngày {date}',
    openItem: 'Mở {name}',
    choosePrinter: 'Chọn máy in',
    jobStatuses: {
      Draft: 'Nháp',
      Submitted: 'Đã gửi',
      'Pending review': 'Chờ duyệt',
      Approved: 'Đã duyệt',
      Scheduled: 'Đã lên lịch',
      Printing: 'Đang in',
      Done: 'Hoàn thành',
      Rejected: 'Từ chối',
      Cancelled: 'Đã hủy',
      'Needs Revision': 'Cần chỉnh sửa',
    },
    materialSources: {
      Personal: 'Tự mang',
      Lab: 'Mua từ lab',
    },
    save: 'Lưu',
  },
  pageMeta: {
    dashboard: { eyebrow: '// Không gian làm việc', title: 'Tổng quan vận hành', note: 'Theo dõi yêu cầu, kiểm duyệt hàng đợi và quản lý vật tư.' },
    booking: { eyebrow: '// Tạo yêu cầu', title: 'Yêu cầu in mới', note: 'Chuẩn bị file, vật liệu và ghi chú in trước khi yêu cầu được đưa vào hàng đợi duyệt.' },
    history: { eyebrow: '// Lưu trữ', title: 'Lịch sử yêu cầu', note: 'Xem lại các yêu cầu đã gửi, quyết định xếp lịch và những bản in đã hoàn thành.' },
    queue: { eyebrow: '// Kiểm duyệt', title: 'Hàng đợi duyệt', note: 'Xử lý phê duyệt, yêu cầu chỉnh sửa và áp lực xếp lịch trong hàng đợi hiện tại.' },
    inventory: { eyebrow: '// Vật liệu', title: 'Kho vật liệu', note: 'Theo dõi tồn kho, màu sắc sẵn có và những cuộn filament sắp chạm ngưỡng cảnh báo.' },
    analytics: { eyebrow: '// Bảng giá', title: 'Điều chỉnh bảng giá', note: 'Cập nhật đơn giá vật liệu, phí dịch vụ và các mốc giá tham chiếu của phòng lab.' },
    users: { eyebrow: '// Truy cập', title: 'Danh sách người dùng', note: 'Quản lý tài khoản sinh viên, điều phối viên và các quyền vận hành trong hệ thống.' },
    printers: { eyebrow: '// Máy in', title: 'Điều phối máy in', note: 'Giữ trạng thái sẵn sàng, độ dài hàng đợi và thông tin từng máy luôn đồng bộ.' },
    chat: { eyebrow: '// Trao đổi', title: 'Trao đổi trong lab', note: 'Giữ liên lạc giữa sinh viên, điều phối viên và nhân sự vận hành trong cùng một luồng trao đổi.' },
    backup: { eyebrow: '// Sao lưu', title: 'Bản sao lưu hệ thống', note: 'Bảo vệ dữ liệu runtime, các file xuất ra và những mốc khôi phục của không gian làm việc.' },
    settings: { eyebrow: '// Cấu hình', title: 'Cài đặt phòng lab', note: 'Điều chỉnh thiết lập mặc định, kênh liên hệ và các quy tắc vận hành cấp hệ thống.' },
    pricing: { eyebrow: '// Công khai', title: 'Tổng quan bảng giá', note: 'Cung cấp cho sinh viên bảng tham chiếu rõ ràng về vật liệu, phụ phí và chi phí in.' },
    'queue-status': { eyebrow: '// Hàng đợi', title: 'Trạng thái hàng chờ', note: 'Xem tải hiện tại, công việc sắp tới và vị trí của từng yêu cầu trong hàng đợi.' },
    'job-detail': { eyebrow: '// Chi tiết', title: 'Chi tiết yêu cầu', note: 'Kiểm tra file, ghi chú và kết quả xử lý của một yêu cầu in cụ thể.' },
  },
  roles: {
    studentSpace: 'Không gian sinh viên', moderatorSpace: 'Web điều phối', adminSpace: 'Quản trị viên',
    sidebarStudent: 'Không gian sinh viên', sidebarModerator: 'Bàn duyệt hàng đợi', sidebarAdmin: 'Quản trị vận hành',
    admin: 'Quản trị', moderator: 'Điều phối', student: 'Sinh viên',
  },
  sidebar: {
    mobileEyebrow: '// Điều hướng', mobileTitle: 'Web điều phối', brandEyebrow: '// Phòng in 3D', brandTitle: 'Web điều phối',
    brandNote: 'Theo dõi yêu cầu, kiểm duyệt hàng chờ và giữ trạng thái máy in, vật tư.', sectionLabel: '// Không gian làm việc', logout: 'Đăng xuất',
    nav: { dashboard: 'Tổng quan', booking: 'Tạo yêu cầu in', history: 'Lịch sử yêu cầu', pricing: 'Bảng giá', 'queue-status': 'Hàng chờ', queue: 'Hàng đợi duyệt', printers: 'Máy in', inventory: 'Vật tư', users: 'Người dùng', analytics: 'Bảng giá & phí', backup: 'Sao lưu', settings: 'Thiết lập', chat: 'Trao đổi' },
  },
  adminPrinters: {
    heroEyebrow: '// Máy in', heroTitle: 'Theo dõi công suất, trạng thái máy và phân bổ theo từng cơ sở.', heroDesc: 'Nhóm máy theo cơ sở, cập nhật trạng thái vận hành ngay tại chỗ và giữ hồ sơ ảnh, vật liệu hỗ trợ luôn khớp với đội máy thực tế.', refresh: 'Làm mới đội máy', add: 'Thêm máy in', loading: 'Đang tải đội máy in...', empty: 'Chưa có máy in nào được cấu hình.', createFirst: 'Tạo máy in đầu tiên',
    stats: { fleet: { label: 'Đội máy in', note: 'Toàn bộ máy in đang được cấu hình và theo dõi trong hệ thống.' }, available: { label: 'Sẵn sàng ngay', note: 'Máy có thể nhận job mới mà không cần xử lý thủ công thêm.' }, ams: { label: 'Có AMS', note: 'Máy hỗ trợ đổi vật liệu hoặc in đa màu qua AMS.' }, busy: { label: 'Đang bận', note: 'Máy đang chạy hoặc đã được giữ chỗ cho các job hiện tại.' } },
    campusLabel: 'Cơ sở', campusNote: '{count} máy đang được quản lý tại cơ sở này để điều phối vận hành và lên kế hoạch bảo trì.', campusTotal: '{count} tổng', campusAvailable: '{count} sẵn sàng', profile: 'Hồ sơ máy', supportedMaterials: 'Vật liệu hỗ trợ', campusField: 'Cơ sở', campusFieldNote: 'Cập nhật trạng thái ngay khi máy đổi sang bận hoặc bảo trì.', edit: 'Sửa', statusAvailable: 'Sẵn sàng', statusBusy: 'Đang bận', statusMaintenance: 'Bảo trì', deleteConfirm: 'Xóa máy in "{name}"? Hành động này không thể hoàn tác.', validationName: 'Vui lòng nhập tên máy in và thể tích in.', validationMaterial: 'Hãy chọn ít nhất một loại vật liệu được hỗ trợ.', modalEyebrow: '// Hồ sơ máy in', modalEditTitle: 'Chỉnh sửa hồ sơ máy', modalAddTitle: 'Thêm máy in mới', modalDesc: 'Giữ ảnh máy, dải vật liệu hỗ trợ và trạng thái vận hành luôn khớp với đội máy thực tế.', preview: 'Xem trước', uploadImage: 'Tải ảnh máy in', imageUrlPlaceholder: 'Hoặc dán URL ảnh', printerName: 'Tên máy in', printerNamePlaceholder: 'Bambu Lab A1 / Ender 3 / X1 Carbon', buildVolume: 'Thể tích in', buildVolumePlaceholder: '256 x 256 x 256 mm', selectCampus: 'Cơ sở', customCampusPlaceholder: 'Nhãn cơ sở tùy chỉnh', selectMaterials: 'Vật liệu hỗ trợ', hasAms: 'Hỗ trợ AMS', hasAmsDesc: 'Dùng cho các máy có thể gắn nhiều cuộn vật liệu hoặc tự động chuyển màu, chuyển vật liệu.', statusField: 'Trạng thái vận hành', cancel: 'Hủy', saveAdd: 'Tạo máy in', saveEdit: 'Lưu thay đổi máy in',
  },
  adminInventory: {
    heroEyebrow: '// Vật tư', heroTitle: 'Theo dõi từng cuộn vật liệu trước khi hàng chờ chạm ngưỡng thiếu hụt.', heroDesc: 'Giữ trạng thái tồn kho theo từng cơ sở, cập nhật số gram còn lại theo thời gian thực và phát hiện điểm nghẽn trước khi điều phối viên gặp thiếu vật liệu giữa ca in.', refresh: 'Làm mới tồn kho', add: 'Thêm cuộn vật liệu', closeAdd: 'Đóng biểu mẫu nhập cuộn', loading: 'Đang tải tồn kho vật liệu...',
    stats: { pla: { label: 'Tồn PLA', note: 'Lượng PLA sẵn sàng cho các yêu cầu in phổ biến của sinh viên.' }, petg: { label: 'Tồn PETG', note: 'Phần tồn cho các job cần độ bền hoặc điều kiện sử dụng cao hơn.' }, low: { label: 'Cuộn cần bổ sung', note: 'Những cuộn sắp hết hoặc đã hết cần được rà soát và bổ sung thêm.' }, tracked: { label: 'Cuộn đang theo dõi', note: 'Tổng số cuộn vật liệu đang được theo dõi xuyên suốt các cơ sở.' } },
    deleteConfirm: 'Xóa cuộn vật liệu này khỏi tồn kho?', newEyebrow: '// Nhập cuộn mới', newTitle: 'Ghi nhận một cuộn vật liệu mới vào bảng tồn kho.', newDesc: 'Nhập cơ sở, chất liệu, màu, thương hiệu và ngưỡng cảnh báo trong một lượt để cả nhóm nhìn cùng một trạng thái tồn kho.', requiredHint: 'Bắt buộc: chất liệu + màu', area: 'Cơ sở', material: 'Chất liệu', brand: 'Thương hiệu', brandPlaceholder: 'Bambu, eSUN, Elegoo...', location: 'Vị trí lưu', locationPlaceholder: 'Kệ A1 / Tầng 2', color: 'Màu', selectPresetColor: 'Chọn màu có sẵn', customColor: 'Màu tùy chỉnh', customColorPlaceholder: 'Nhập tên màu tùy chỉnh', remainingGrams: 'Khối lượng hiện tại (g)', threshold: 'Ngưỡng cảnh báo (g)', saveReel: 'Lưu cuộn vật liệu', collapseForm: 'Thu gọn biểu mẫu', boardEyebrow: '// Bảng tồn kho', boardTitle: 'Đọc tồn kho theo từng cơ sở rồi chỉ cập nhật phần vừa thay đổi.', boardDesc: 'Tìm theo mã cuộn, chất liệu, thương hiệu hoặc màu để cả lab giữ chung một mặt nhìn tồn kho.', visibleCount: '{count} cuộn hiển thị', reviewCount: '{count} cuộn cần rà soát', searchPlaceholder: 'Tìm mã cuộn, chất liệu, màu hoặc thương hiệu', areaEyebrow: 'Kệ vật tư', areaNote: '{count} cuộn đang được quản lý trong vùng tồn kho của cơ sở này.', areaCount: '{count} cuộn', lowCount: '{count} sắp hết', emptyArea: 'Chưa có cuộn nào trong cơ sở này.', noBrand: 'Chưa có thương hiệu', noShelf: 'Chưa gán vị trí', updateStock: 'Cập nhật tồn', deleteReel: 'Xóa cuộn', stockRemaining: '{count}g còn lại', stockThreshold: 'Ngưỡng {count}g', inStock: 'Còn hàng', lowStock: 'Sắp hết', outOfStock: 'Hết hàng', reelId: 'Mã cuộn', actions: 'Tác vụ', disciplineEyebrow: 'Kỷ luật tồn kho', disciplineNote: 'Các cuộn ở trạng thái sắp hết nên được rà soát trước khi gán cho một lượt in mới.',
  },
  adminUsers: {
    noDate: 'Chưa có mốc thời gian', permanent: 'Không thời hạn', heroEyebrow: 'Admin / Quản trị người dùng', heroTitle: 'Kiểm soát quyền truy cập trước khi tài khoản chạm tới luồng vận hành của lab.', heroDesc: 'Rà soát đăng ký, thay đổi quyền trách nhiệm và giữ các tài khoản rủi ro ra khỏi hàng đợi máy in.', tabs: { users: 'Bảng tài khoản', warnings: 'Bảng cảnh báo' },
    stats: { total: { label: 'Tài khoản trong hệ thống', note: 'Toàn bộ tài khoản sinh viên và vận hành đã đăng ký.' }, active: { label: 'Đang hoạt động', note: 'Những thành viên hiện có thể sử dụng luồng làm việc của lab.' }, pending: { label: 'Chờ duyệt', note: 'Các tài khoản đang đợi phê duyệt thủ công.' }, staff: { label: 'Nhân sự vận hành', note: 'Các vị trí admin và moderator đang được cấp quyền.' } },
    roleLabels: { Admin: 'Quản trị', Moderator: 'Điều phối', Student: 'Sinh viên' }, statusLabels: { active: 'Đang hoạt động', pending: 'Chờ duyệt', suspended: 'Tạm khóa' }, deleteConfirm: 'Xóa tài khoản "{name}"? Hành động này không thể hoàn tác và sẽ xóa cả các yêu cầu in liên quan.', riskEyebrow: 'Bảng rủi ro', riskCount: '{count} tài khoản hiện đang bị chặn khỏi luồng làm việc của lab.', noSuspended: 'Không có tài khoản nào đang bị khóa.', noSuspendedNote: 'Bảng này chỉ sáng lên khi một tài khoản bị chặn tạm thời hoặc vĩnh viễn khỏi luồng vận hành.', temporaryHold: 'Tạm khóa', permanentHold: 'Khóa vô thời hạn', restoreAccess: 'Khôi phục truy cập', blockReason: 'Lý do khóa', noReason: 'Chưa có lý do đính kèm.', restrictionWindow: 'Thời hạn hạn chế', restrictionNote: 'Tài khoản sẽ bị chặn cho đến khi nhóm vận hành gỡ cảnh báo.', approvalEyebrow: 'Áp lực phê duyệt', approvalCount: '{count} tài khoản đang chờ phê duyệt trước khi có thể gửi yêu cầu in.', filterPending: 'Lọc chờ duyệt', boardEyebrow: 'Bảng tài khoản', boardTitle: 'Sắp xếp quyền truy cập, quyền vai trò và trạng thái kiểm duyệt.', boardDesc: 'Tìm theo danh sách thành viên, thay đổi quyền nhân sự và xử lý tài khoản rủi ro mà không rời khỏi bảng.', visibleCount: '{count} đang hiển thị', suspendedCount: '{count} đang khóa', searchPlaceholder: 'Tìm tên, email hoặc mã sinh viên', allStatuses: 'Tất cả trạng thái', refresh: 'Làm mới bảng', loading: 'Đang tải bảng tài khoản...', noMatch: 'Không có tài khoản nào khớp với bộ lọc hiện tại.', noMatchNote: 'Hãy mở rộng từ khóa tìm kiếm hoặc đổi bộ lọc trạng thái kiểm duyệt.', noStudentId: 'Chưa có mã sinh viên', table: { user: 'Người dùng', contact: 'Liên hệ', joined: 'Tham gia', role: 'Vai trò', status: 'Trạng thái', actions: 'Tác vụ' }, mobileJoined: 'Ngày tạo', approve: 'Duyệt', suspend: 'Khóa', restore: 'Khôi phục', delete: 'Xóa', modalEyebrow: 'Tạm khóa kiểm duyệt', modalTitle: 'Tạm khóa {name}', modalDesc: 'Chọn thời hạn khóa, ghi lại lý do và giữ quyết định này luôn có thể truy vết cho các moderator khác.', timedHold: 'Khóa có thời hạn', timedHoldDesc: 'Tự động khôi phục quyền truy cập sau khoảng thời gian đã chọn.', permanentHoldDesc: 'Giữ tài khoản bị chặn cho đến khi nhân sự vận hành mở lại thủ công.', suspensionWindow: 'Thời hạn khóa', days: '{count} ngày', reason: 'Lý do', reasonPlaceholder: 'Mô tả vi phạm chính sách hoặc lý do kiểm duyệt...', cancel: 'Hủy', confirmSuspension: 'Xác nhận tạm khóa',
  },
  adminPricing: {
    heroEyebrow: 'Admin / Điều phối giá', heroTitle: 'Đặt các con số quyết định báo giá trước khi job bước vào sản xuất.', heroDesc: 'Điều chỉnh giá vật liệu, bật hoặc tắt phụ phí và xem ngay ảnh hưởng bằng bộ ước tính nhanh.', save: 'Lưu thay đổi bảng giá', saved: 'Đã lưu trạng thái bảng giá',
    stats: { pla: { label: 'Mốc PLA', note: 'Mức giá tham chiếu được dùng trong bộ ước tính nhanh bên dưới.' }, fees: { label: 'Phí đang bật', note: 'Các khoản phụ phí đang tham gia vào tổng chi phí.' } },
    materialEyebrow: 'Giá vật liệu', materialTitle: 'Đơn giá theo gram cho từng nhóm filament.', materialDesc: 'Mỗi thay đổi chỉ áp dụng cho những yêu cầu tạo sau thời điểm bạn lưu.', loadingMaterials: 'Đang tải bảng giá vật liệu...', futureRequests: 'Đơn giá cho các yêu cầu sắp tạo', vndPerGram: 'VND / gram', serviceEyebrow: 'Phí dịch vụ', serviceTitle: 'Phụ phí, chi phí xử lý và các công tắc vận hành.', serviceDesc: 'Bật, tắt hoặc điều chỉnh phụ phí mà không phải đụng vào giá nền của vật liệu.', loadingFees: 'Đang tải phụ phí dịch vụ...', feeLabels: { setup_fee: 'Phí khởi tạo job', rush_fee: 'Phí in nhanh', service_fee: 'Phí in hộ' }, feeDescriptions: { setup_fee: 'Áp dụng cho mỗi yêu cầu in cần qua quy trình tiếp nhận ban đầu.', rush_fee: 'Ưu tiên hàng đợi cho các yêu cầu cần xử lý sớm hơn bình thường.', service_fee: 'Phí dịch vụ in hộ tính theo gram vật liệu tiêu thụ.' }, perGram: 'Tính theo gram', enabled: 'Đang bật', disabled: 'Đang tắt', active: 'Đang hoạt động', inactive: 'Tạm tắt', flatFee: 'VND / lần', policyEyebrow: 'Chính sách giá', policyNote: 'Giá mới chỉ áp dụng cho các job được tạo sau khi bạn lưu. Job cũ giữ nguyên mức giá lúc được tạo.', estimatorEyebrow: 'Bộ ước tính nhanh', estimatorTitle: 'Kiểm tra ngay tác động của mức giá PLA hiện tại.', estimatorDesc: 'Bản xem nhanh này giúp bạn đối chiếu một mức báo giá nền trước khi áp dụng cho cả hàng đợi.', estimatorInput: 'Khối lượng vật liệu', estimatorTotal: 'Tổng PLA ước tính',
  },
  adminSettings: {
    success: 'Đã lưu cài đặt thành công.', loading: 'Đang tải cài đặt...', heroEyebrow: 'Admin / Cài đặt công khai', heroTitle: 'Điều chỉnh lớp thông tin sinh viên nhìn thấy trước khi họ cần hỗ trợ.', heroDesc: 'Những giá trị này đi vào landing page và các điểm chạm hỗ trợ, nên thông tin công khai luôn chính xác mà không cần sửa code.',
    stats: { channels: { label: 'Kênh hỗ trợ', value: '4', note: 'Email, Facebook, Zalo và đường dẫn hướng dẫn đều được quản lý từ bảng này.' }, publish: { label: 'Mô hình xuất bản', value: 'Đang áp dụng', note: 'Thay đổi được áp dụng qua admin API ngay khi bạn lưu cài đặt.' } },
    directoryEyebrow: 'Danh bạ hỗ trợ', directoryTitle: 'Các kênh liên hệ và hướng dẫn công khai.', directoryDesc: 'Để trống một trường nếu bạn không muốn kênh đó xuất hiện ở giao diện công khai.', supportEmail: 'Email hỗ trợ', supportEmailHint: 'Hộp thư chính để nhận các câu hỏi về lab và luồng vận hành.', facebookPage: 'Trang Facebook', facebookPageHint: 'Kênh công khai để cập nhật thông tin hoặc hướng dẫn đặt in.', zaloNumber: 'Số Zalo', zaloNumberHint: 'Kênh nhắn nhanh cho các câu hỏi ngắn hoặc việc theo dõi vận hành.', guideUrl: 'Đường dẫn hướng dẫn', guideUrlHint: 'Link tài liệu hoặc handbook cho người dùng mới.', saving: 'Đang lưu cài đặt...',
  },
  adminBackup: {
    heroEyebrow: 'Admin / Kho sao lưu', heroTitle: 'Giữ bản chụp hệ thống trong tầm tay trước khi khôi phục trở nên gấp gáp.', heroDesc: 'Tạo bản sao lưu thủ công, rà soát danh sách lưu trữ và tải đúng snapshot bạn muốn giữ ngoài hệ thống.', refresh: 'Làm mới sao lưu', create: 'Tạo bản sao lưu ngay', createdAlert: 'Đã tạo bản sao lưu: {file}',
    stats: { files: { label: 'Tệp sao lưu', note: 'Các snapshot hiện đang hiển thị trong thư mục sao lưu.' }, weight: { label: 'Dung lượng lưu trữ', note: 'Tổng dung lượng của toàn bộ gói sao lưu đang được liệt kê.' } },
    archiveEyebrow: 'Danh sách lưu trữ', archiveTitle: 'Rà soát từng snapshot trước khi xuất.', latestPrefix: 'Bản mới nhất: {date}.', noBackupsYet: 'Chưa có bản sao lưu nào.', filesCount: '{count} tệp', latestSize: '{size} gần nhất', loading: 'Đang tải kho sao lưu...', empty: 'Chưa có gói sao lưu nào.', emptyNote: 'Tạo một snapshot thủ công để chụp lại trạng thái hệ thống hiện tại trước khi bảo trì hoặc triển khai.', download: 'Tải xuống', retentionEyebrow: 'Ghi chú lưu trữ', retentionNote: 'Mỗi gói sao lưu đều chứa dữ liệu vận hành. Hãy lưu file tải xuống ở nơi được kiểm soát và tránh chia sẻ ra ngoài nhóm lab.',
  },
  adminOverview: {
    heroEyebrow: '// Bảng điều phối',
    heroTitle: 'Bảng điều phối vận hành',
    heroDesc: 'Quan sát áp lực hàng đợi, khối lượng duyệt và nhịp vận hành máy in từ một bảng điều phối duy nhất.',
    historyEyebrow: '// Lưu trữ',
    historyTitle: 'Mỗi yêu cầu, một dòng thời gian.',
    historyDesc: 'Tìm theo tên yêu cầu hoặc mã ID, sau đó lọc theo trạng thái để xem lại toàn bộ hành trình xử lý.',
    historySearchPlaceholder: 'Tìm kiếm yêu cầu',
    historyMatches: 'Số yêu cầu khớp',
    historyEmptyTitle: 'Không có yêu cầu nào khớp với bộ lọc hiện tại.',
    historyEmptyDesc: 'Thử đổi trạng thái hoặc từ khóa tìm kiếm để mở rộng kết quả trong phần lưu trữ.',
    viewHistory: 'Xem lịch sử',
    viewArchive: 'Xem lưu trữ',
    userCardTitle: 'Người dùng',
    openRequestsTitle: 'Yêu cầu đang mở',
    openRequestsNote: 'Các yêu cầu vẫn đang đi trong luồng xử lý.',
    attentionTitle: 'Cần chú ý',
    attentionNote: 'Các yêu cầu đang chờ cập nhật file hoặc ghi chú.',
    needsRevisionEyebrow: '// Cần chỉnh sửa',
    needsRevisionTitle: '{count} yêu cầu cần được cập nhật trước khi in.',
    processingEyebrow: '// Yêu cầu đang xử lý',
    processingTitle: 'Tất cả yêu cầu',
    actionsEyebrow: '// Thao tác',
    actionsTitle: 'Kiểm tra hàng đợi.',
    actionsDesc: 'Chỉnh sửa và xếp lịch in.',
    shortcutsEyebrow: '// Lối tắt',
    trackingEyebrow: '// Theo dõi trạng thái',
    labStatsEyebrow: '// Thống kê lab',
    sevenDayEyebrow: '// Nhịp 7 ngày',
    quickQueueStatus: 'Trạng thái hàng đợi',
    metrics: {
      pending: { label: 'Yêu cầu đang chờ', note: 'Đang chờ duyệt hoặc xếp lịch' },
      total: { label: 'Tổng số yêu cầu', note: 'Tổng số yêu cầu trong phạm vi hiện tại' },
      printing: { label: 'Đang in', note: 'Đang chạy trên máy in' },
      done: { label: 'Đã hoàn thành', note: 'Đã hoàn thành và ghi nhận' },
    },
    historyFilters: {
      all: 'Tất cả trạng thái',
    },
    chartLegend: {
      done: 'Hoàn thành',
      approved: 'Đã duyệt',
      rejected: 'Từ chối',
      revision: 'Chỉnh sửa',
    },
    table: {
      request: 'Yêu cầu',
      printer: 'Máy in',
      material: 'Loại nhựa (Material)',
      status: 'Trạng thái',
      open: 'Mở',
    },
  },
  moderatorQueue: {
    heroEyebrow: '// Hàng đợi duyệt',
    heroTitle: 'Giữ luồng kiểm duyệt gọn, rõ và không bị tắc.',
    heroDesc: 'Tìm yêu cầu cần xử lý, xem nhanh thông tin vật liệu và thao tác ngay trong cùng một bàn điều phối. Tất cả thay đổi trạng thái đều phản ánh trực tiếp vào hàng đợi.',
    cards: {
      pending: { label: 'Chờ duyệt', note: 'Các yêu cầu cần kiểm tra trước khi chốt lịch in.' },
      printing: { label: 'Đang in', note: 'Những job đã được đưa lên máy và đang chạy.' },
      revision: { label: 'Cần sửa', note: 'Các yêu cầu đang chờ sinh viên bổ sung hoặc chỉnh lại file.' },
    },
    listEyebrow: '// Danh sách chờ xử lý',
    listCount: '{count} yêu cầu đang mở',
    refresh: 'Làm mới',
    searchPlaceholder: 'Tìm theo tên yêu cầu, người gửi hoặc mã job',
    loading: 'Đang tải danh sách...',
    emptyTitle: 'Không có yêu cầu nào khớp với bộ lọc hiện tại.',
    emptyDesc: 'Thử đổi từ khóa tìm kiếm hoặc làm mới danh sách để lấy dữ liệu mới nhất.',
    selectTitle: 'Chọn một yêu cầu để xem chi tiết.',
    selectDesc: 'Khi chọn một job ở cột trái, toàn bộ thông tin kiểm duyệt và thao tác vận hành sẽ xuất hiện ở đây.',
    profileEyebrow: '// Hồ sơ yêu cầu',
    requestedBy: 'Yêu cầu bởi {user} · {id}',
    openDetail: 'Mở chi tiết',
    statusQuickTitle: 'Chuyển trạng thái nhanh',
    currentStatus: 'Trạng thái hiện tại: {status}',
    changeTo: 'Chuyển sang...',
    summary: {
      material: 'Vật liệu',
      estimatedGrams: 'Khối lượng ước tính',
      materialSource: 'Nguồn nhựa',
      estimatedTime: 'Thời lượng dự kiến',
    },
    quoteEyebrow: 'Báo giá lại',
    quoteDesc: 'Sau khi slice file, nhập khối lượng nhựa thực tế để hệ thống tính lại chi phí chính xác cho sinh viên.',
    quoteGrams: 'Gram ước tính mới',
    quoteCost: 'Chi phí dự kiến',
    quoteSaved: 'Đã cập nhật báo giá thành công.',
    quoteSave: 'Lưu báo giá mới',
    printingEyebrow: '// Đang in',
    printingMachine: 'Máy in: {name}',
    printingDesc: 'Khi job hoàn tất, nhập khối lượng thực tế rồi đánh dấu hoàn thành.',
    actualGrams: 'Khối lượng thực tế (gram)',
    actualGramsPlaceholder: 'Nhập sau khi in xong',
    markDone: 'Đánh dấu hoàn thành',
    cancelJob: 'Hủy job',
    readyEyebrow: '// Sẵn sàng in',
    assignPrinter: 'Gán máy in',
    startPrinting: 'Bắt đầu in',
    moderationEyebrow: '// Thao tác kiểm duyệt',
    approve: 'Phê duyệt',
    requestRevision: 'Yêu cầu chỉnh sửa',
    reject: 'Từ chối',
    assignPrinterFirst: 'Gán máy in trước',
    revisionNoteAlert: 'Vui lòng nhập nội dung yêu cầu sửa trong ô ghi chú.',
    moderatorNoteEyebrow: '// Ghi chú moderator',
    moderatorNotePlaceholder: 'Nhập lý do từ chối hoặc nội dung cần sinh viên chỉnh sửa...',
    noPrinter: 'Chưa gán',
    confirmStatus: 'Chuyển trạng thái từ "{from}" sang "{to}"?',
    actionError: 'Có lỗi xảy ra.',
    updateError: 'Cập nhật thất bại.',
  },
} as const;

const jpOverrides = {
  shared: {
    loadingWorkspace: 'Loading workspace', userLabel: 'User', statusLabel: 'Status', statusOnline: 'Lab online', refresh: 'Refresh', languageLabel: 'Language', languageToggle: 'Switch language', languageNames: { VN: 'Vietnamese', JP: 'English' }, themeLabel: 'Theme', themeToggle: 'Switch theme', themeLight: 'Light mode', themeDark: 'Dark mode', openNavigation: 'Open navigation', closeNavigation: 'Close navigation', closeOverlay: 'Close navigation overlay', backDashboard: 'Back to overview', systemUser: 'System user', pageUnavailable: 'This page is still being polished.', pageLoadFailed: 'Unable to load this request.', jobDetailSelectedNote: 'Review request {id} together with the related operation notes.', noDate: 'No date', noDuration: 'No duration yet', notAssigned: 'Unassigned', waitingApproval: 'Pending review', createdOn: 'Created on {date}', openItem: 'Open {name}', choosePrinter: 'Choose a printer', jobStatuses: { Draft: 'Draft', Submitted: 'Submitted', 'Pending review': 'Pending review', Approved: 'Approved', Scheduled: 'Scheduled', Printing: 'Printing', Done: 'Done', Rejected: 'Rejected', Cancelled: 'Cancelled', 'Needs Revision': 'Needs revision' }, materialSources: { Personal: 'Personal supply', Lab: 'Lab stock' },
    save: 'Save'
  },
  pageMeta: {
    dashboard: { eyebrow: '// Workspace', title: 'Operations overview', note: 'Track requests, review load and manage material state.' },
    booking: { eyebrow: '// New request', title: 'New print request', note: 'Prepare file, material and notes before the request enters the review queue.' },
    history: { eyebrow: '// Archive', title: 'Request history', note: 'Review sent requests, scheduling decisions and completed prints.' },
    queue: { eyebrow: '// Moderation', title: 'Review queue', note: 'Approve, request revisions and balance the current queue.' },
    inventory: { eyebrow: '// Materials', title: 'Material stock', note: 'Track stock, available colors and warning thresholds.' },
    analytics: { eyebrow: '// Pricing', title: 'Pricing controls', note: 'Adjust material rates, service fees and quote references.' },
    users: { eyebrow: '// Access', title: 'User roster', note: 'Manage student accounts, staff roles and moderation status.' },
    printers: { eyebrow: '// Printers', title: 'Printer operations', note: 'Keep readiness, fleet state and printer details in sync.' },
    chat: { eyebrow: '// Messaging', title: 'Lab conversation', note: 'Keep students and operators in the same thread.' },
    backup: { eyebrow: '// Backups', title: 'System backups', note: 'Protect runtime data, exported files and recovery checkpoints.' },
    settings: { eyebrow: '// Settings', title: 'Lab settings', note: 'Adjust defaults, contact channels and operational rules.' },
    pricing: { eyebrow: '// Public', title: 'Pricing overview', note: 'Show students a clean reference for materials, surcharges and print cost.' },
    'queue-status': { eyebrow: '// Queue', title: 'Queue status', note: 'Inspect current load, upcoming work and request order.' },
    'job-detail': { eyebrow: '// Detail', title: 'Request detail', note: 'Inspect files, notes and the processing trail of one request.' },
  },
  sidebar: { mobileEyebrow: '// Navigation', mobileTitle: 'Operations web', brandEyebrow: '// 3D print room', brandTitle: 'Operations web', brandNote: 'Track requests, review the queue and keep printer and material state aligned.', sectionLabel: '// Workspace', logout: 'Log out', nav: { dashboard: 'Overview', booking: 'Create request', history: 'Request history', pricing: 'Pricing', 'queue-status': 'Queue', queue: 'Review queue', printers: 'Printers', inventory: 'Materials', users: 'Users', analytics: 'Pricing & fees', backup: 'Backups', settings: 'Settings', chat: 'Messages' } },
  roles: { studentSpace: 'Student workspace', moderatorSpace: 'Operations web', adminSpace: 'Administrator', sidebarStudent: 'Student workspace', sidebarModerator: 'Review desk', sidebarAdmin: 'Operations admin', admin: 'Admin', moderator: 'Moderator', student: 'Student' },
  adminPrinters: {
    heroEyebrow: '// Printers',
    heroTitle: 'Track capacity, printer state and campus allocation from one board.',
    heroDesc: 'Group machines by campus, update live operating state and keep image and material profiles aligned with the real fleet.',
    refresh: 'Refresh fleet',
    add: 'Add printer',
    loading: 'Loading printer fleet...',
    empty: 'No printers have been configured yet.',
    createFirst: 'Create the first printer',
    stats: {
      fleet: { label: 'Fleet size', note: 'Every printer currently tracked by the system.' },
      available: { label: 'Ready now', note: 'Printers that can receive new jobs immediately.' },
      ams: { label: 'AMS ready', note: 'Machines that support material switching or multi-color prints.' },
      busy: { label: 'Busy now', note: 'Printers currently printing or reserved for active jobs.' },
    },
    campusLabel: 'Campus',
    campusNote: '{count} printers are currently managed in this campus zone.',
    campusTotal: '{count} total',
    campusAvailable: '{count} ready',
    profile: 'Printer profile',
    supportedMaterials: 'Supported materials',
    campusField: 'Campus',
    campusFieldNote: 'Update the state as soon as a printer becomes busy or enters maintenance.',
    edit: 'Edit',
    statusAvailable: 'Available',
    statusBusy: 'Busy',
    statusMaintenance: 'Maintenance',
    deleteConfirm: 'Delete printer "{name}"? This action cannot be undone.',
    validationName: 'Please enter the printer name and build volume.',
    validationMaterial: 'Please choose at least one supported material.',
    modalEyebrow: '// Printer profile',
    modalEditTitle: 'Edit printer profile',
    modalAddTitle: 'Add a new printer',
    modalDesc: 'Keep image, supported materials and operating state aligned with the real machine.',
    preview: 'Preview',
    uploadImage: 'Upload printer image',
    imageUrlPlaceholder: 'Or paste an image URL',
    printerName: 'Printer name',
    printerNamePlaceholder: 'Bambu Lab A1 / Ender 3 / X1 Carbon',
    buildVolume: 'Build volume',
    buildVolumePlaceholder: '256 x 256 x 256 mm',
    selectCampus: 'Campus',
    customCampusPlaceholder: 'Custom campus label',
    selectMaterials: 'Supported materials',
    hasAms: 'AMS support',
    hasAmsDesc: 'Use this for printers that can hold multiple reels or switch material and color automatically.',
    statusField: 'Operating status',
    cancel: 'Cancel',
    saveAdd: 'Create printer',
    saveEdit: 'Save changes',
  },
  adminInventory: {
    heroEyebrow: '// Materials',
    heroTitle: 'Track every reel before the queue hits a shortage threshold.',
    heroDesc: 'Keep stock state by campus, update grams in real time and spot bottlenecks before operators run out of material mid-shift.',
    refresh: 'Refresh stock',
    add: 'Add material reel',
    closeAdd: 'Close intake form',
    loading: 'Loading material stock...',
    stats: {
      pla: { label: 'PLA stock', note: 'PLA available for common student requests.' },
      petg: { label: 'PETG stock', note: 'Stock reserved for jobs needing more strength or heat resistance.' },
      low: { label: 'Needs refill', note: 'Reels that are low or empty and should be replenished.' },
      tracked: { label: 'Tracked reels', note: 'Total number of reels monitored across campuses.' },
    },
    deleteConfirm: 'Remove this material reel from stock?',
    newEyebrow: '// New reel',
    newTitle: 'Record a new material reel in the stock board.',
    newDesc: 'Capture campus, material, color, brand and warning threshold in one pass so the whole team sees the same inventory state.',
    requiredHint: 'Required: material + color',
    area: 'Campus',
    material: 'Material',
    brand: 'Brand',
    brandPlaceholder: 'Bambu, eSUN, Elegoo...',
    location: 'Storage location',
    locationPlaceholder: 'Shelf A1 / Level 2',
    color: 'Color',
    selectPresetColor: 'Choose a preset color',
    customColor: 'Custom color',
    customColorPlaceholder: 'Enter a custom color name',
    remainingGrams: 'Current weight (g)',
    threshold: 'Warning threshold (g)',
    saveReel: 'Save material reel',
    collapseForm: 'Collapse form',
    boardEyebrow: '// Stock board',
    boardTitle: 'Read stock by campus and update only what changed.',
    boardDesc: 'Search by reel ID, material, brand or color so everyone works from the same stock view.',
    visibleCount: '{count} visible reels',
    reviewCount: '{count} need review',
    searchPlaceholder: 'Search reel ID, material, color or brand',
    areaEyebrow: 'Material shelf',
    areaNote: '{count} reels are currently managed in this campus zone.',
    areaCount: '{count} reels',
    lowCount: '{count} low',
    emptyArea: 'No reels are registered in this campus zone yet.',
    noBrand: 'No brand',
    noShelf: 'No shelf',
    updateStock: 'Update stock',
    deleteReel: 'Delete reel',
    stockRemaining: '{count}g left',
    stockThreshold: 'Threshold {count}g',
    inStock: 'In stock',
    lowStock: 'Low',
    outOfStock: 'Out of stock',
    reelId: 'Reel ID',
    actions: 'Actions',
    disciplineEyebrow: 'Stock discipline',
    disciplineNote: 'Low-stock reels should be reviewed before they get assigned to a new print run.',
  },
  adminUsers: {
    noDate: 'No date',
    permanent: 'Permanent',
    heroEyebrow: 'Admin / User governance',
    heroTitle: 'Shape access before an account reaches the lab floor.',
    heroDesc: 'Review registrations, switch role responsibility and keep risky accounts outside the printer flow.',
    tabs: { users: 'Account board', warnings: 'Suspension board' },
    stats: {
      total: { label: 'Accounts in system', note: 'Every student and operator account currently registered.' },
      active: { label: 'Active access', note: 'Members who can currently use the lab flow.' },
      pending: { label: 'Pending review', note: 'Accounts waiting for manual approval.' },
      staff: { label: 'Lab staff roles', note: 'Admin and moderator seats currently in circulation.' },
    },
    roleLabels: { Admin: 'Admin', Moderator: 'Moderator', Student: 'Student' },
    statusLabels: { active: 'Active', pending: 'Pending', suspended: 'Suspended' },
    deleteConfirm: 'Delete account "{name}"? This cannot be undone and will remove related print requests.',
    riskEyebrow: 'Risk board',
    riskCount: '{count} accounts are currently blocked from the lab flow.',
    noSuspended: 'No suspended accounts.',
    noSuspendedNote: 'This board lights up only when an account has been temporarily or permanently removed from the workflow.',
    temporaryHold: 'Temporary hold',
    permanentHold: 'Permanent hold',
    restoreAccess: 'Restore access',
    blockReason: 'Block reason',
    noReason: 'No reason attached.',
    restrictionWindow: 'Restriction window',
    restrictionNote: 'The account stays unavailable until staff clears the warning.',
    approvalEyebrow: 'Approval pressure',
    approvalCount: '{count} accounts are waiting for approval before they can submit jobs.',
    filterPending: 'Filter pending',
    boardEyebrow: 'Account board',
    boardTitle: 'Sort access, role ownership and moderation state.',
    boardDesc: 'Search the roster, promote staff roles and action risky accounts without leaving the board.',
    visibleCount: '{count} visible',
    suspendedCount: '{count} suspended',
    searchPlaceholder: 'Search name, email or student ID',
    allStatuses: 'All statuses',
    refresh: 'Refresh board',
    loading: 'Loading account board...',
    noMatch: 'No accounts match the current filter.',
    noMatchNote: 'Try widening the search or changing the moderation status filter.',
    noStudentId: 'No student ID',
    table: { user: 'User', contact: 'Contact', joined: 'Joined', role: 'Role', status: 'Status', actions: 'Actions' },
    mobileJoined: 'Joined',
    approve: 'Approve',
    suspend: 'Suspend',
    restore: 'Restore',
    delete: 'Delete',
    modalEyebrow: 'Moderation hold',
    modalTitle: 'Suspend {name}',
    modalDesc: 'Choose a suspension window, log the reason and keep the decision traceable for other moderators.',
    timedHold: 'Timed hold',
    timedHoldDesc: 'Restore access automatically after the chosen window.',
    permanentHoldDesc: 'Keep the account blocked until staff restores it manually.',
    suspensionWindow: 'Suspension window',
    days: '{count} days',
    reason: 'Reason',
    reasonPlaceholder: 'Describe the policy breach or moderation reason...',
    cancel: 'Cancel',
    confirmSuspension: 'Confirm suspension',
  },
  adminPricing: {
    heroEyebrow: 'Admin / Pricing control',
    heroTitle: 'Set the numbers that define every quote before a job hits production.',
    heroDesc: 'Tune material prices, enable or disable surcharges and preview the effect immediately with a lightweight estimator.',
    save: 'Save pricing changes',
    saved: 'Saved pricing state',
    stats: {
      pla: { label: 'PLA baseline', note: 'The reference price used in the quick estimator below.' },
      fees: { label: 'Active fees', note: 'Service charges currently contributing to the total.' },
    },
    materialEyebrow: 'Material pricing',
    materialTitle: 'Per-gram pricing by filament family.',
    materialDesc: 'Each rate updates future requests only. Existing jobs keep the price they were created with.',
    loadingMaterials: 'Loading material pricing...',
    futureRequests: 'Filament pricing for future requests',
    vndPerGram: 'VND / gram',
    serviceEyebrow: 'Service fees',
    serviceTitle: 'Surcharges, handling costs and operational toggles.',
    serviceDesc: 'Enable, disable or adjust fees without touching the material baseline.',
    loadingFees: 'Loading service fees...',
    feeLabels: {
      setup_fee: 'Job setup fee',
      rush_fee: 'Rush fee',
      service_fee: 'Operator assist fee',
    },
    feeDescriptions: {
      setup_fee: 'Applies to each request entering intake.',
      rush_fee: 'Prioritizes a request in the queue.',
      service_fee: 'Charged per gram of consumed material.',
    },
    perGram: 'Per gram',
    enabled: 'Enabled',
    disabled: 'Disabled',
    active: 'Active',
    inactive: 'Inactive',
    flatFee: 'VND flat fee',
    policyEyebrow: 'Pricing policy',
    policyNote: 'New prices apply only to jobs created after you save the board. Historical jobs keep their original numbers.',
    estimatorEyebrow: 'Quick estimator',
    estimatorTitle: 'Check the immediate effect of the current PLA pricing.',
    estimatorDesc: 'This preview helps you sanity-check a baseline quote before pushing changes to the whole queue.',
    estimatorInput: 'Material grams',
    estimatorTotal: 'Estimated PLA total',
  },
  adminSettings: {
    success: 'Settings saved successfully.',
    loading: 'Loading settings...',
    heroEyebrow: 'Admin / Public settings',
    heroTitle: 'Shape the contact layer students see before they ask for help.',
    heroDesc: 'These values feed the landing page and support touchpoints, so the public guidance stays accurate without touching code.',
    stats: {
      channels: { label: 'Support channels', value: '4', note: 'Email, Facebook, Zalo and guide URL are all managed from this board.' },
      publish: { label: 'Publishing model', value: 'Live', note: 'Changes are applied through the admin API as soon as you save.' },
    },
    directoryEyebrow: 'Support directory',
    directoryTitle: 'Contact channels and public guidance.',
    directoryDesc: 'Leave a field empty if you do not want that channel to appear publicly.',
    supportEmail: 'Support email',
    supportEmailHint: 'Primary inbox for lab support and workflow questions.',
    facebookPage: 'Facebook page',
    facebookPageHint: 'Public social channel for updates or booking guidance.',
    zaloNumber: 'Zalo number',
    zaloNumberHint: 'Fast messaging channel for short questions or operational follow-up.',
    guideUrl: 'Guide URL',
    guideUrlHint: 'Documentation or handbook link for first-time users.',
    saving: 'Saving settings...',
  },
  adminBackup: {
    heroEyebrow: 'Admin / Backup vault',
    heroTitle: 'Keep recovery snapshots close before restoration becomes urgent.',
    heroDesc: 'Create manual backups, review the archive list and download the exact snapshot you want to store outside the system.',
    refresh: 'Refresh backups',
    create: 'Create backup now',
    createdAlert: 'Backup created: {file}',
    stats: {
      files: { label: 'Backup files', note: 'Snapshots currently visible in the backup directory.' },
      weight: { label: 'Storage weight', note: 'Total size of the backup packages currently listed.' },
    },
    archiveEyebrow: 'Archive list',
    archiveTitle: 'Review each snapshot before export.',
    latestPrefix: 'Latest snapshot: {date}.',
    noBackupsYet: 'No backups yet.',
    filesCount: '{count} files',
    latestSize: '{size} latest',
    loading: 'Loading backup inventory...',
    empty: 'No backup archives yet.',
    emptyNote: 'Create a snapshot before maintenance or deployment.',
    download: 'Download',
    retentionEyebrow: 'Retention note',
    retentionNote: 'Each archive contains production data. Store exported files securely.',
  },
  adminOverview: { heroEyebrow: '// Control board', heroTitle: 'Operations overview', heroDesc: 'Watch queue pressure, review load and printer rhythm from one control surface.', historyEyebrow: '// Archive', historyTitle: 'Every request, one timeline.', historyDesc: 'Search by request name or ID, then filter by status to review the full processing trail.', historySearchPlaceholder: 'Search requests', historyMatches: 'Matching requests', historyEmptyTitle: 'No requests match the current filters.', historyEmptyDesc: 'Try a different status or search term to widen the archive results.', viewHistory: 'View history', viewArchive: 'View archive', userCardTitle: 'User', openRequestsTitle: 'Open requests', openRequestsNote: 'Requests still moving through the workflow.', attentionTitle: 'Needs attention', attentionNote: 'Requests waiting for updated files or notes.', needsRevisionEyebrow: '// Needs revision', needsRevisionTitle: '{count} requests need updates before printing.', processingEyebrow: '// In progress', processingTitle: 'All requests', actionsEyebrow: '// Actions', actionsTitle: 'Review the queue.', actionsDesc: 'Adjust and schedule print work.', shortcutsEyebrow: '// Shortcuts', trackingEyebrow: '// Status tracking', labStatsEyebrow: '// Lab stats', sevenDayEyebrow: '// 7-day pulse', quickQueueStatus: 'Queue status', metrics: { pending: { label: 'Pending requests', note: 'Waiting for review or scheduling' }, total: { label: 'Total requests', note: 'All requests in the current scope' }, printing: { label: 'Printing', note: 'Currently running on machines' }, done: { label: 'Completed', note: 'Finished and recorded' } }, historyFilters: { all: 'All statuses' }, chartLegend: { done: 'Done', approved: 'Approved', rejected: 'Rejected', revision: 'Revision' }, table: { request: 'Request', printer: 'Printer', material: 'Material', status: 'Status', open: 'Open' } },
  moderatorQueue: { heroEyebrow: '// Review queue', heroTitle: 'Keep moderation crisp, visible and unblocked.', heroDesc: 'Find the next request to process, inspect material details quickly and act from the same workstation. Every state change flows straight back into the queue.', cards: { pending: { label: 'Pending review', note: 'Requests waiting for a moderation decision before scheduling.' }, printing: { label: 'Printing', note: 'Jobs already assigned to a machine and currently running.' }, revision: { label: 'Needs revision', note: 'Requests waiting for students to update files or notes.' } }, listEyebrow: '// Requests to process', listCount: '{count} open requests', refresh: 'Refresh', searchPlaceholder: 'Search by request name, sender or job ID', loading: 'Loading queue...', emptyTitle: 'No requests match the current filters.', emptyDesc: 'Try a different search term or refresh the list to pull the latest data.', selectTitle: 'Choose a request to inspect.', selectDesc: 'Once you select a job on the left, all moderation details and operating controls appear here.', profileEyebrow: '// Request profile', requestedBy: 'Requested by {user} · {id}', openDetail: 'Open detail', statusQuickTitle: 'Quick status switch', currentStatus: 'Current status: {status}', changeTo: 'Change to...', summary: { material: 'Material', estimatedGrams: 'Estimated weight', materialSource: 'Material source', estimatedTime: 'Estimated duration' }, quoteEyebrow: 'Requote', quoteDesc: 'After slicing the file, enter the actual material estimate so the system can recalculate the quote for the student.', quoteGrams: 'New gram estimate', quoteCost: 'Projected cost', quoteSaved: 'Quote updated successfully.', quoteSave: 'Save new quote', printingEyebrow: '// Printing', printingMachine: 'Printer: {name}', printingDesc: 'When the job finishes, enter the actual grams and mark it complete.', actualGrams: 'Actual grams', actualGramsPlaceholder: 'Enter after printing finishes', markDone: 'Mark complete', cancelJob: 'Cancel job', readyEyebrow: '// Ready to print', assignPrinter: 'Assign printer', startPrinting: 'Start printing', moderationEyebrow: '// Moderation actions', approve: 'Approve', requestRevision: 'Request revision', reject: 'Reject', assignPrinterFirst: 'Assign a printer first', revisionNoteAlert: 'Enter the revision request in the moderator notes field first.', moderatorNoteEyebrow: '// Moderator notes', moderatorNotePlaceholder: 'Add the rejection reason or the changes the student needs to make...', noPrinter: 'Not assigned', confirmStatus: 'Change status from "{from}" to "{to}"?', actionError: 'Something went wrong.', updateError: 'Update failed.' },
} as const;

function deepMerge<T extends Record<string, any>>(base: T, override: Record<string, any>): T {
  const result: Record<string, any> = Array.isArray(base) ? [...base] : { ...base };
  for (const [key, value] of Object.entries(override)) {
    const current = result[key];
    result[key] = value && typeof value === 'object' && !Array.isArray(value) && current && typeof current === 'object' && !Array.isArray(current)
      ? deepMerge(current, value)
      : value;
  }
  return result as T;
}

export const uiText = {
  VN: vnText,
  JP: deepMerge(vnText, jpOverrides),
} as const;

export const translations = {
  VN: {
    appName: 'BCSE 3D Lab',
    appSubtitle: 'VJU My Dinh Â· VJU Hoa Lac',
    labOnline: 'Lab Ä‘ang hoáº¡t Ä‘á»™ng',
    welcome: 'ChÃ o má»«ng trá»Ÿ láº¡i',
    registerTitle: 'ÄÄƒng kÃ½ tÃ i khoáº£n',
    loginSubtitle: 'ÄÄƒng nháº­p Ä‘á»ƒ quáº£n lÃ½ yÃªu cáº§u in 3D cá»§a báº¡n.',
    registerSubtitle: 'Tham gia khÃ´ng gian in 3D cá»§a VJU-BCSE Lab.',
    login: 'ÄÄƒng nháº­p',
    register: 'ÄÄƒng kÃ½',
    registerNow: 'ÄÄƒng kÃ½ ngay',
    logout: 'ÄÄƒng xuáº¥t',
    email: 'Email',
    emailPlaceholder: 'name@st.vju.ac.vn',
    emailHint: 'Chá»‰ cháº¥p nháº­n email @st.vju.ac.vn hoáº·c @vju.ac.vn',
    password: 'Máº­t kháº©u',
    fullName: 'Há» vÃ  tÃªn',
    studentId: 'MÃ£ sinh viÃªn',
    phone: 'Sá»‘ Ä‘iá»‡n thoáº¡i',
    supervisor: 'Giáº£ng viÃªn hÆ°á»›ng dáº«n (tÃ¹y chá»n)',
    registerSuccess: 'ÄÄƒng kÃ½ thÃ nh cÃ´ng. Báº¡n cÃ³ thá»ƒ Ä‘Äƒng nháº­p ngay bÃ¢y giá».',
    invalidEmail: 'Chá»‰ cháº¥p nháº­n email VJU (@st.vju.ac.vn hoáº·c @vju.ac.vn)',
    dashboard: 'Tá»•ng quan',
    booking: 'Táº¡o yÃªu cáº§u in',
    history: 'Lá»‹ch sá»­ yÃªu cáº§u',
    queue: 'HÃ ng Ä‘á»£i duyá»‡t',
    inventory: 'Váº­t tÆ°',
    analytics: 'Báº£ng giÃ¡',
    users: 'NgÆ°á»i dÃ¹ng',
    printers: 'MÃ¡y in',
    chat: 'Trao Ä‘á»•i',
    backup: 'Sao lÆ°u',
    settings: 'Thiáº¿t láº­p',
    pendingJobs: 'YÃªu cáº§u Ä‘ang chá»',
    totalJobs: 'Tá»•ng sá»‘ yÃªu cáº§u',
    printing: 'Äang in',
    done: 'HoÃ n thÃ nh',
    myJobs: 'YÃªu cáº§u cá»§a tÃ´i',
    allJobs: 'Táº¥t cáº£ yÃªu cáº§u',
    noJobs: 'ChÆ°a cÃ³ yÃªu cáº§u nÃ o',
    newRequest: 'Táº¡o yÃªu cáº§u má»›i',
    readyToPrint: 'Sáºµn sÃ ng in?',
    readyToPrintDesc: 'Táº¡o yÃªu cáº§u má»›i vÃ  báº¯t Ä‘áº§u dá»± Ã¡n cá»§a báº¡n ngay hÃ´m nay.',
    quickActions: 'Thao tÃ¡c nhanh',
    statusTracking: 'Theo dÃµi tráº¡ng thÃ¡i',
    labStats: 'Thá»‘ng kÃª lab',
    viewAllHistory: 'Xem toÃ n bá»™ lá»‹ch sá»­',
    pendingApproval: 'Chá» duyá»‡t',
    activeUsers: 'NgÆ°á»i dÃ¹ng hoáº¡t Ä‘á»™ng',
    step1: 'HÃ¬nh thá»©c',
    step2: 'Váº­t liá»‡u',
    step3: 'File',
    step4: 'MÃ¡y & lá»‹ch',
    step5: 'XÃ¡c nháº­n',
    printMode: 'HÃ¬nh thá»©c in',
    selfPrint: 'Tá»± in',
    selfPrintDesc: 'Báº¡n tá»± váº­n hÃ nh mÃ¡y táº¡i lab.',
    labAssisted: 'In há»™',
    labAssistedDesc: 'Lab váº­n hÃ nh mÃ¡y cho báº¡n.',
    slicedFileRequired: 'YÃªu cáº§u file Ä‘Ã£ slice (.gcode hoáº·c .gcode.3mf)',
    slicedFileNote: 'Vui lÃ²ng slice model báº±ng Bambu Studio, Cura hoáº·c pháº§n má»m tÆ°Æ¡ng Ä‘Æ°Æ¡ng trÆ°á»›c khi táº£i lÃªn.',
    labWillSlice: 'Lab sáº½ tá»± slice file vÃ  bÃ¡o giÃ¡ trÆ°á»›c khi in.',
    waitingQuote: 'Chá» duyá»‡t vÃ  bÃ¡o giÃ¡',
    waitingSchedule: 'Chá» xáº¿p lá»‹ch',
    jobName: 'TÃªn yÃªu cáº§u in',
    jobNamePlaceholder: 'VÃ­ dá»¥: Vá» há»™p Arduino',
    purpose: 'Má»¥c Ä‘Ã­ch sá»­ dá»¥ng',
    purposePlaceholder: 'MÃ´ táº£ ngáº¯n gá»n má»¥c Ä‘Ã­ch in cá»§a báº¡n',
    uploadFile: 'Táº£i file lÃªn (STL/3MF)',
    uploadHint: 'KÃ©o tháº£ hoáº·c nháº¥n Ä‘á»ƒ táº£i file lÃªn',
    uploadNote: 'Há»— trá»£ .stl, .3mf, tá»‘i Ä‘a 50MB',
    uploadSuccess: 'Táº£i file thÃ nh cÃ´ng',
    deleteFile: 'XÃ³a file',
    estimatedTime: 'Thá»i gian in Æ°á»›c tÃ­nh',
    estimatedTimeHint: 'Láº¥y tá»« pháº§n má»m slicer sau khi slice model.',
    hours: 'Giá»',
    minutes: 'PhÃºt',
    estimatedGrams: 'Khá»‘i lÆ°á»£ng nhá»±a Æ°á»›c tÃ­nh',
    estimatedGramsHint: 'Láº¥y tá»« pháº§n má»m slicer sau khi slice model.',
    selectPrinter: 'Chá»n mÃ¡y in',
    printerAvailable: 'Sáºµn sÃ ng',
    printerBusy: 'Äang báº­n',
    printerMaintenance: 'Báº£o trÃ¬',
    printerAMS: 'AMS Â· Äa mÃ u',
    queue_length: 'HÃ ng Ä‘á»£i',
    materialType: 'Loáº¡i nhá»±a',
    color: 'MÃ u',
    colorAMS: '(AMS - tá»‘i Ä‘a 4 mÃ u)',
    colorSelected: 'ÄÃ£ chá»n',
    materialSource: 'Nguá»“n váº­t liá»‡u',
    ownMaterial: 'Nhá»±a tá»± mang',
    ownMaterialDesc: 'Báº¡n tá»± cung cáº¥p cuá»™n nhá»±a cho lab.',
    labMaterial: 'Mua nhá»±a tá»« lab',
    labMaterialDesc: 'Sá»­ dá»¥ng nhá»±a cÃ³ sáºµn táº¡i lab.',
    costEstimate: 'Æ¯á»›c tÃ­nh chi phÃ­',
    total: 'Tá»•ng cá»™ng',
    payLater: 'Thanh toÃ¡n sau',
    freeMaterial: 'Miá»…n phÃ­ váº­t liá»‡u',
    preferredDate: 'NgÃ y mong muá»‘n',
    timeSlot: 'Khung giá»',
    timezone: 'MÃºi giá»: Asia/Bangkok (UTC+7)',
    scheduleNote: 'Khung giá» báº¡n chá»n lÃ  mong muá»‘n. Moderator sáº½ chá»‘t lá»‹ch dá»±a trÃªn hÃ ng Ä‘á»£i thá»±c táº¿.',
    reviewRequest: 'Kiá»ƒm tra láº¡i yÃªu cáº§u',
    reviewSubtitle: 'Vui lÃ²ng xÃ¡c nháº­n cÃ¡c thÃ´ng tin dÆ°á»›i Ä‘Ã¢y lÃ  chÃ­nh xÃ¡c.',
    confirmCheckbox: 'TÃ´i xÃ¡c nháº­n Ä‘Ã£ kiá»ƒm tra file in vÃ  tuÃ¢n thá»§ quy Ä‘á»‹nh an toÃ n cá»§a lab.',
    submitRequest: 'Gá»­i yÃªu cáº§u',
    back: 'Quay láº¡i',
    next: 'Tiáº¿p tá»¥c',
    cancel: 'Há»§y',
    notNamed: 'ChÆ°a Ä‘áº·t tÃªn',
    notSelected: 'ChÆ°a chá»n',
    notAssigned: 'ChÆ°a xáº¿p',
    waitingApproval: 'Chá» duyá»‡t',
    area: 'Khu vá»±c',
    attachment: 'Tá»‡p Ä‘Ã­nh kÃ¨m',
    printerName: 'MÃ¡y in',
    slicerFrom: 'Nguá»“n nhá»±a',
    statusDraft: 'NhÃ¡p',
    statusSubmitted: 'ÄÃ£ gá»­i',
    statusPendingReview: 'Chá» duyá»‡t',
    statusApproved: 'ÄÃ£ duyá»‡t',
    statusScheduled: 'ÄÃ£ lÃªn lá»‹ch',
    statusPrinting: 'Äang in',
    statusDone: 'HoÃ n thÃ nh',
    statusRejected: 'Tá»« chá»‘i',
    statusCancelled: 'ÄÃ£ há»§y',
    heroTitle: 'Gá»­i yÃªu cáº§u in 3D',
    heroHighlight: 'nhanh vÃ  rÃµ rÃ ng',
    heroDesc: 'Há»‡ thá»‘ng quáº£n lÃ½ yÃªu cáº§u in 3D dÃ nh cho sinh viÃªn vÃ  nhÃ¢n sá»± váº­n hÃ nh cá»§a VJU-BCSE Lab.',
    featurePolicy: 'Quy trÃ¬nh rÃµ rÃ ng',
    featurePolicyDesc: 'Má»i yÃªu cáº§u Ä‘á»u Ä‘i qua quy trÃ¬nh kiá»ƒm duyá»‡t trÆ°á»›c khi lÃªn mÃ¡y.',
    featureMaterial: 'Váº­t liá»‡u linh hoáº¡t',
    featureMaterialDesc: 'Tá»± mang nhá»±a hoáº·c dÃ¹ng váº­t liá»‡u cÃ³ sáºµn táº¡i lab.',
    featureSafe: 'An toÃ n vÃ  kiá»ƒm soÃ¡t',
    featureSafeDesc: 'Quáº£n lÃ½ tÃ i khoáº£n, tráº¡ng thÃ¡i mÃ¡y in vÃ  lá»‹ch sá»­ yÃªu cáº§u trong má»™t há»‡ thá»‘ng thá»‘ng nháº¥t.',
    userGuide: 'HÆ°á»›ng dáº«n sá»­ dá»¥ng',
    contactSupport: 'LiÃªn há»‡ há»— trá»£',
    copyright: 'Â© 2026 VJU-BCSE Lab',
    loading: 'Äang táº£i...',
    loadingData: 'Äang táº£i dá»¯ liá»‡u...',
    loadingPrinters: 'Äang táº£i mÃ¡y in...',
    error: 'Lá»—i',
    serverError: 'KhÃ´ng thá»ƒ káº¿t ná»‘i mÃ¡y chá»§. Vui lÃ²ng kiá»ƒm tra láº¡i backend.',
    retry: 'Thá»­ láº¡i',
    save: 'LÆ°u',
    edit: 'Chá»‰nh sá»­a',
    delete: 'XÃ³a',
    confirm: 'XÃ¡c nháº­n',
    close: 'ÄÃ³ng',
    search: 'TÃ¬m kiáº¿m',
    noData: 'KhÃ´ng cÃ³ dá»¯ liá»‡u',
    morning: 'SÃ¡ng',
    afternoon: 'Chiá»u',
    evening: 'Tá»‘i',
    morning_range: '08:00 - 12:00',
    afternoon_range: '13:00 - 17:00',
    evening_range: '18:00 - 22:00',
    pricePerGram: 'Ä‘/g',
    gram: 'gram',
    notSet: 'ChÆ°a thiáº¿t láº­p',
  },
  JP: {
    appName: 'BCSE 3D Lab',
    appSubtitle: 'VJU My Dinh Â· VJU Hoa Lac',
    labOnline: 'Lab online',
    welcome: 'Welcome back',
    registerTitle: 'Create account',
    loginSubtitle: 'Sign in to manage your 3D print requests.',
    registerSubtitle: 'Join the 3D printing workspace of VJU-BCSE Lab.',
    login: 'Log in',
    register: 'Register',
    registerNow: 'Register now',
    logout: 'Log out',
    email: 'Email',
    emailPlaceholder: 'name@st.vju.ac.vn',
    emailHint: 'Only @st.vju.ac.vn or @vju.ac.vn emails are accepted',
    password: 'Password',
    fullName: 'Full name',
    studentId: 'Student ID',
    phone: 'Phone number',
    supervisor: 'Supervisor (optional)',
    registerSuccess: 'Registration successful. You can sign in now.',
    invalidEmail: 'Only VJU email addresses are accepted (@st.vju.ac.vn or @vju.ac.vn)',
    dashboard: 'Overview',
    booking: 'Create request',
    history: 'Request history',
    queue: 'Review queue',
    inventory: 'Materials',
    analytics: 'Pricing',
    users: 'Users',
    printers: 'Printers',
    chat: 'Messages',
    backup: 'Backups',
    settings: 'Settings',
    pendingJobs: 'Pending requests',
    totalJobs: 'Total requests',
    printing: 'Printing',
    done: 'Completed',
    myJobs: 'My requests',
    allJobs: 'All requests',
    noJobs: 'No requests yet',
    newRequest: 'New request',
    readyToPrint: 'Ready to print?',
    readyToPrintDesc: 'Create a new request and start your project today.',
    quickActions: 'Quick actions',
    statusTracking: 'Status tracking',
    labStats: 'Lab stats',
    viewAllHistory: 'View full history',
    pendingApproval: 'Pending approval',
    activeUsers: 'Active users',
    step1: 'Mode',
    step2: 'Material',
    step3: 'File',
    step4: 'Printer & time',
    step5: 'Confirm',
    printMode: 'Print mode',
    selfPrint: 'Self print',
    selfPrintDesc: 'You operate the printer at the lab.',
    labAssisted: 'Operator assist',
    labAssistedDesc: 'Lab staff operate the printer for you.',
    slicedFileRequired: 'A sliced file is required (.gcode or .gcode.3mf)',
    slicedFileNote: 'Please slice the model in Bambu Studio, Cura or an equivalent tool before upload.',
    labWillSlice: 'The lab will slice the file and confirm the quote before printing.',
    waitingQuote: 'Waiting for review and quote',
    waitingSchedule: 'Waiting for scheduling',
    jobName: 'Request name',
    jobNamePlaceholder: 'Example: Arduino enclosure',
    purpose: 'Purpose',
    purposePlaceholder: 'Briefly describe what this print is for',
    uploadFile: 'Upload file (STL/3MF)',
    uploadHint: 'Drag and drop or click to upload',
    uploadNote: 'Supports .stl, .3mf, max 50MB',
    uploadSuccess: 'Upload successful',
    deleteFile: 'Delete file',
    estimatedTime: 'Estimated print time',
    estimatedTimeHint: 'Take this from your slicer after slicing the model.',
    hours: 'Hours',
    minutes: 'Minutes',
    estimatedGrams: 'Estimated material usage',
    estimatedGramsHint: 'Take this from your slicer after slicing the model.',
    selectPrinter: 'Choose a printer',
    printerAvailable: 'Available',
    printerBusy: 'Busy',
    printerMaintenance: 'Maintenance',
    printerAMS: 'AMS Â· Multi-color',
    queue_length: 'Queue',
    materialType: 'Material type',
    color: 'Color',
    colorAMS: '(AMS - up to 4 colors)',
    colorSelected: 'Selected',
    materialSource: 'Material source',
    ownMaterial: 'Bring your own filament',
    ownMaterialDesc: 'You provide the filament reel.',
    labMaterial: 'Use lab material',
    labMaterialDesc: 'Use material currently stocked by the lab.',
    costEstimate: 'Estimated cost',
    total: 'Total',
    payLater: 'Pay later',
    freeMaterial: 'Free material',
    preferredDate: 'Preferred date',
    timeSlot: 'Time slot',
    timezone: 'Timezone: Asia/Bangkok (UTC+7)',
    scheduleNote: 'Your selected slot is a preference. A moderator will confirm the final schedule based on queue load.',
    reviewRequest: 'Review your request',
    reviewSubtitle: 'Please confirm the information below is correct.',
    confirmCheckbox: 'I confirm that I checked the file and will follow the lab safety rules.',
    submitRequest: 'Submit request',
    back: 'Back',
    next: 'Next',
    cancel: 'Cancel',
    notNamed: 'Unnamed',
    notSelected: 'Not selected',
    notAssigned: 'Unassigned',
    waitingApproval: 'Pending review',
    area: 'Area',
    attachment: 'Attachment',
    printerName: 'Printer',
    slicerFrom: 'Material source',
    statusDraft: 'Draft',
    statusSubmitted: 'Submitted',
    statusPendingReview: 'Pending review',
    statusApproved: 'Approved',
    statusScheduled: 'Scheduled',
    statusPrinting: 'Printing',
    statusDone: 'Completed',
    statusRejected: 'Rejected',
    statusCancelled: 'Cancelled',
    heroTitle: 'Submit a 3D print request',
    heroHighlight: 'quickly and clearly',
    heroDesc: 'A 3D print request workspace for students and lab operators at VJU-BCSE.',
    featurePolicy: 'Clear workflow',
    featurePolicyDesc: 'Every request goes through review before it reaches a printer.',
    featureMaterial: 'Flexible materials',
    featureMaterialDesc: 'Bring your own filament or use material stocked by the lab.',
    featureSafe: 'Controlled and safe',
    featureSafeDesc: 'Accounts, printer state and request history stay under one system.',
    userGuide: 'User guide',
    contactSupport: 'Contact support',
    copyright: 'Â© 2026 VJU-BCSE Lab',
    loading: 'Loading...',
    loadingData: 'Loading data...',
    loadingPrinters: 'Loading printers...',
    error: 'Error',
    serverError: 'Unable to connect to the server. Please check the backend.',
    retry: 'Retry',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    confirm: 'Confirm',
    close: 'Close',
    search: 'Search',
    noData: 'No data',
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
    morning_range: '08:00 - 12:00',
    afternoon_range: '13:00 - 17:00',
    evening_range: '18:00 - 22:00',
    pricePerGram: 'VND/g',
    gram: 'g',
    notSet: 'Not set',
  },
} as const;

export type TranslationKey = keyof typeof translations.VN;
export type UiText = typeof uiText.VN;
export type UiLang = Lang;

export function getUiText(lang: Lang) {
  return uiText[lang] ?? uiText.VN;
}

export function fillText(template: string, params?: Record<string, string | number>) {
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, key) => String(params[key] ?? ''));
}


