export type Lang = 'VN' | 'JP';


const vnText = {
  shared: {
    loadingWorkspace: 'Đang tải không gian làm việc',
    userLabel: 'Người dùng',
    statusLabel: 'Trạng thái',
    statusOnline: 'Lab đang hoạt động',
    refresh: 'Làm mới',
    languageLabel: 'Ngôn ngữ',
    languageToggle: 'Chuyển ngôn ngữ',
    languageNames: { VN: 'Tiếng Việt', JP: 'English' },
    themeLabel: 'Giao diện',
    themeToggle: 'Chuyển giao diện',
    themeLight: 'Chế độ sáng',
    themeDark: 'Chế độ tối',
    openNavigation: 'Mở điều hướng',
    closeNavigation: 'Đóng điều hướng',
    closeOverlay: 'Đóng lớp phủ điều hướng',
    backDashboard: 'Quay về tổng quan',
    systemUser: 'Người dùng hệ thống',
    pageUnavailable: 'Trang này vẫn đang trong quá trình hoàn thiện.',
    pageLoadFailed: 'Dữ liệu không phản hồi, không thể mở trang hệ thống.',
    jobDetailSelectedNote: 'Xem lại yêu cầu in {id} và các ghi chú vận hành đi kèm.',
    noDate: 'Chưa chốt thời gian',
    noDuration: 'Tính sau khi slice',
    notAssigned: 'Chưa báo lịch',
    waitingApproval: 'Chờ Lab duyệt',
    createdOn: 'Ngày tạo: {date}',
    openItem: 'Mở chi tiết {name}',
    choosePrinter: 'Chọn chức năng máy in',
    jobStatuses: {
      Draft: 'Lưu nháp',
      Submitted: 'Đã gửi yêu cầu',
      'Pending review': 'Chờ Lab duyệt',
      Approved: 'Đã duyệt báo giá',
      Scheduled: 'Đã lên lịch ấn định',
      Printing: 'Đang chạy máy',
      Done: 'Đã in xong',
      Rejected: 'Lab từ chối',
      Cancelled: 'Đã hủy',
      'Needs Revision': 'Cần bạn sửa lại',
    },
    materialSources: {
      Personal: 'Tự mang',
      Lab: 'Mua từ lab',
    },
    save: 'Lưu',
  },
  pageMeta: {
    dashboard: { eyebrow: '// Không gian làm việc', title: 'Tổng quan vận hành', note: 'Theo dõi yêu cầu, kiểm duyệt hàng đợi và quản lý vật tư.' },
    booking: { eyebrow: '// Tạo yêu cầu', title: 'Yêu cầu in mới', note: 'Chuẩn bị file, vật liệu và ghi chú in trước khi yêu cầu được đưa vào hàng đợi duyệt.' },
    history: { eyebrow: '// Lưu trữ', title: 'Lịch sử yêu cầu', note: 'Xem lại các yêu cầu đã gửi, quyết định xếp lịch và những bản in đã hoàn thành.' },
    queue: { eyebrow: '// Kiểm duyệt', title: 'Hàng đợi duyệt', note: 'Xử lý phê duyệt, yêu cầu chỉnh sửa và áp lực xếp lịch trong hàng đợi hiện tại.' },
    inventory: { eyebrow: '// Vật liệu', title: 'Kho vật liệu', note: 'Theo dõi tồn kho, màu sắc sẵn có và những cuộn filament sắp chạm ngưỡng cảnh báo.' },
    analytics: { eyebrow: '// Bảng giá', title: 'Điều chỉnh bảng giá', note: 'Cập nhật đơn giá vật liệu, phí dịch vụ và các mốc giá tham chiếu của phòng lab.' },
    users: { eyebrow: '// Truy cập', title: 'Danh sách người dùng', note: 'Quản lý tài khoản sinh viên, điều phối viên và các quyền vận hành trong hệ thống.' },
    printers: { eyebrow: '// Máy in', title: 'Điều phối máy in', note: 'Giữ trạng thái sẵn sàng, độ dài hàng đợi và thông tin từng máy luôn đồng bộ.' },
    chat: { eyebrow: '// Trao đổi', title: 'Trao đổi trong lab', note: 'Giữ liên lạc giữa sinh viên, điều phối viên và nhân sự vận hành trong cùng một luồng trao đổi.' },
    backup: { eyebrow: '// Sao lưu', title: 'Bản sao lưu hệ thống', note: 'Bảo vệ dữ liệu runtime, các file xuất ra và những mốc khôi phục của không gian làm việc.' },
    settings: { eyebrow: '// Cấu hình', title: 'Cài đặt phòng lab', note: 'Điều chỉnh thiết lập mặc định, kênh liên hệ và các quy tắc vận hành cấp hệ thống.' },
    pricing: { eyebrow: '// Công khai', title: 'Tổng quan bảng giá', note: 'Cung cấp cho sinh viên bảng tham chiếu rõ ràng về vật liệu, phụ phí và chi phí in.' },
    'queue-status': { eyebrow: '// Hàng đợi', title: 'Trạng thái hàng chờ', note: 'Xem tải hiện tại, công việc sắp tới và vị trí của từng yêu cầu trong hàng đợi.' },
    'job-detail': { eyebrow: '// Chi tiết', title: 'Chi tiết yêu cầu', note: 'Kiểm tra file, ghi chú và kết quả xử lý của một yêu cầu in cụ thể.' },
  },
  roles: {
    studentSpace: 'Góc Của Bạn', moderatorSpace: 'Trạm Điều Phối In', adminSpace: 'Phòng Quản Trị Tổng',
    sidebarStudent: 'Góc Của Bạn', sidebarModerator: 'Trạm Điều Phối In', sidebarAdmin: 'Quản Trị Vận Hành',
    admin: 'Quản Trị Thượng Tầng', moderator: 'Mod Điều Phối', student: 'Thành viên In',
  },
  sidebar: {
    mobileEyebrow: '// Menu Trạm Xử Lý', mobileTitle: 'Trạm Điều Phối', brandEyebrow: '// Xưởng In 3D Mở', brandTitle: 'Trạm Điều Phối In',
    brandNote: 'Giữ hàng đợi lưu thông, bắt rủi ro file hỏng, cân đối vật liệu kho giữa các Mod với nhau.', sectionLabel: '// Bảng Điều Khiển Chính', logout: 'Thoát tài khoản',
    nav: { dashboard: 'Toàn cảnh Lab', booking: 'Ném File & Lên Lịch', history: 'Toàn bộ Lịch sử thao tác', pricing: 'Bảng cước hao hụt', 'queue-status': 'Tình trạng kẹt máy', queue: 'Trạm kiểm luồng', printers: 'Dàn máy trực chiến', inventory: 'Bãi đáp cuộn nhựa', users: 'Quản lý Thẻ người dùng', analytics: 'Cấu hình khung phí', backup: 'Vét Khôi Phục Dữ Liệu', settings: 'Tinh chỉnh Lab', chat: 'Kênh Hỏi Đáp & Hối Thúc' },
  },
  adminPrinters: {
    heroEyebrow: '// Máy in', heroTitle: 'Theo dõi công suất, trạng thái máy và phân bổ theo từng cơ sở.', heroDesc: 'Nhóm máy theo cơ sở, cập nhật trạng thái vận hành ngay tại chỗ và giữ hồ sơ ảnh, vật liệu hỗ trợ luôn khớp với đội máy thực tế.', refresh: 'Làm mới đội máy', add: 'Thêm máy in', loading: 'Đang tải đội máy in...', empty: 'Chưa có máy in nào được cấu hình.', createFirst: 'Tạo máy in đầu tiên',
    stats: { fleet: { label: 'Đội máy in', note: 'Toàn bộ máy in đang được cấu hình và theo dõi trong hệ thống.' }, available: { label: 'Sẵn sàng ngay', note: 'Máy có thể nhận job mới mà không cần xử lý thủ công thêm.' }, ams: { label: 'Có AMS', note: 'Máy hỗ trợ đổi vật liệu hoặc in đa màu qua AMS.' }, busy: { label: 'Đang bận', note: 'Máy đang chạy hoặc đã được giữ chỗ cho các job hiện tại.' } },
    campusLabel: 'Cơ sở', campusNote: '{count} máy đang được quản lý tại cơ sở này để điều phối vận hành và lên kế hoạch bảo trì.', campusTotal: '{count} tổng', campusAvailable: '{count} sẵn sàng', profile: 'Hồ sơ máy', supportedMaterials: 'Vật liệu hỗ trợ', campusField: 'Cơ sở', campusFieldNote: 'Cập nhật trạng thái ngay khi máy đổi sang bận hoặc bảo trì.', edit: 'Sửa', statusAvailable: 'Sẵn sàng', statusBusy: 'Đang bận', statusMaintenance: 'Bảo trì', deleteConfirm: 'Xóa máy in "{name}"? Hành động này không thể hoàn tác.', validationName: 'Vui lòng nhập tên máy in và thể tích in.', validationMaterial: 'Hãy chọn ít nhất một loại vật liệu được hỗ trợ.', modalEyebrow: '// Hồ sơ máy in', modalEditTitle: 'Chỉnh sửa hồ sơ máy', modalAddTitle: 'Thêm máy in mới', modalDesc: 'Giữ ảnh máy, dải vật liệu hỗ trợ và trạng thái vận hành luôn khớp với đội máy thực tế.', preview: 'Xem trước', uploadImage: 'Tải ảnh máy in', imageUrlPlaceholder: 'Hoặc dán URL ảnh', printerName: 'Tên máy in', printerNamePlaceholder: 'Bambu Lab A1 / Ender 3 / X1 Carbon', buildVolume: 'Thể tích in', buildVolumePlaceholder: '256 x 256 x 256 mm', selectCampus: 'Cơ sở', customCampusPlaceholder: 'Nhãn cơ sở tùy chỉnh', selectMaterials: 'Vật liệu hỗ trợ', hasAms: 'Hỗ trợ AMS', hasAmsDesc: 'Dùng cho các máy có thể gắn nhiều cuộn vật liệu hoặc tự động chuyển màu, chuyển vật liệu.', statusField: 'Trạng thái vận hành', cancel: 'Hủy', saveAdd: 'Tạo máy in', saveEdit: 'Lưu thay đổi máy in',
  },
  adminInventory: {
    heroEyebrow: '// Vật tư', heroTitle: 'Theo dõi từng cuộn vật liệu trước khi hàng chờ chạm ngưỡng thiếu hụt.', heroDesc: 'Giữ trạng thái tồn kho theo từng cơ sở, cập nhật số gram còn lại theo thời gian thực và phát hiện điểm nghẽn trước khi điều phối viên gặp thiếu vật liệu giữa ca in.', refresh: 'Làm mới tồn kho', add: 'Thêm cuộn vật liệu', closeAdd: 'Đóng biểu mẫu nhập cuộn', loading: 'Đang tải tồn kho vật liệu...',
    stats: { pla: { label: 'Tồn PLA', note: 'Lượng PLA sẵn sàng cho các yêu cầu in phổ biến của sinh viên.' }, petg: { label: 'Tồn PETG', note: 'Phần tồn cho các job cần độ bền hoặc điều kiện sử dụng cao hơn.' }, low: { label: 'Cuộn cần bổ sung', note: 'Những cuộn sắp hết hoặc đã hết cần được rà soát và bổ sung thêm.' }, tracked: { label: 'Cuộn đang theo dõi', note: 'Tổng số cuộn vật liệu đang được theo dõi xuyên suốt các cơ sở.' } },
    deleteConfirm: 'Xóa cuộn vật liệu này khỏi tồn kho?', newEyebrow: '// Nhập cuộn mới', newTitle: 'Ghi nhận một cuộn vật liệu mới vào bảng tồn kho.', newDesc: 'Nhập cơ sở, chất liệu, màu, thương hiệu và ngưỡng cảnh báo trong một lượt để cả nhóm nhìn cùng một trạng thái tồn kho.', requiredHint: 'Bắt buộc: chất liệu + màu', area: 'Cơ sở', material: 'Chất liệu', brand: 'Thương hiệu', brandPlaceholder: 'Bambu, eSUN, Elegoo...', location: 'Vị trí lưu', locationPlaceholder: 'Kệ A1 / Tầng 2', color: 'Màu', selectPresetColor: 'Chọn màu có sẵn', customColor: 'Màu tùy chỉnh', customColorPlaceholder: 'Nhập tên màu tùy chỉnh', remainingGrams: 'Khối lượng hiện tại (g)', threshold: 'Ngưỡng cảnh báo (g)', saveReel: 'Lưu cuộn vật liệu', collapseForm: 'Thu gọn biểu mẫu', boardEyebrow: '// Bảng tồn kho', boardTitle: 'Đọc tồn kho theo từng cơ sở rồi chỉ cập nhật phần vừa thay đổi.', boardDesc: 'Tìm theo mã cuộn, chất liệu, thương hiệu hoặc màu để cả lab giữ chung một mặt nhìn tồn kho.', visibleCount: '{count} cuộn hiển thị', reviewCount: '{count} cuộn cần rà soát', searchPlaceholder: 'Tìm mã cuộn, chất liệu, màu hoặc thương hiệu', areaEyebrow: 'Kệ vật tư', areaNote: '{count} cuộn đang được quản lý trong vùng tồn kho của cơ sở này.', areaCount: '{count} cuộn', lowCount: '{count} sắp hết', emptyArea: 'Chưa có cuộn nào trong cơ sở này.', noBrand: 'Chưa có thương hiệu', noShelf: 'Chưa gán vị trí', updateStock: 'Cập nhật tồn', deleteReel: 'Xóa cuộn', stockRemaining: '{count}g còn lại', stockThreshold: 'Ngưỡng {count}g', inStock: 'Còn hàng', lowStock: 'Sắp hết', outOfStock: 'Hết hàng', reelId: 'Mã cuộn', actions: 'Tác vụ', disciplineEyebrow: 'Kỷ luật tồn kho', disciplineNote: 'Các cuộn ở trạng thái sắp hết nên được rà soát trước khi gán cho một lượt in mới.',
  },
  adminUsers: {
    noDate: 'Chưa có mốc thời gian', permanent: 'Không thời hạn', heroEyebrow: 'Admin / Quản trị người dùng', heroTitle: 'Kiểm soát quyền truy cập trước khi tài khoản chạm tới luồng vận hành của lab.', heroDesc: 'Rà soát đăng ký, thay đổi quyền trách nhiệm và giữ các tài khoản rủi ro ra khỏi hàng đợi máy in.', tabs: { users: 'Bảng tài khoản', warnings: 'Bảng cảnh báo' },
    stats: { total: { label: 'Tài khoản trong hệ thống', note: 'Toàn bộ tài khoản sinh viên và vận hành đã đăng ký.' }, active: { label: 'Đang hoạt động', note: 'Những thành viên hiện có thể sử dụng luồng làm việc của lab.' }, pending: { label: 'Chờ duyệt', note: 'Các tài khoản đang đợi phê duyệt thủ công.' }, staff: { label: 'Nhân sự vận hành', note: 'Các vị trí admin và moderator đang được cấp quyền.' } },
    roleLabels: { Admin: 'Quản trị', Moderator: 'Điều phối', Student: 'Sinh viên' }, statusLabels: { active: 'Đang hoạt động', pending: 'Chờ duyệt', suspended: 'Tạm khóa' }, deleteConfirm: 'Xóa tài khoản "{name}"? Hành động này không thể hoàn tác và sẽ xóa cả các yêu cầu in liên quan.', riskEyebrow: 'Bảng rủi ro', riskCount: '{count} tài khoản hiện đang bị chặn khỏi luồng làm việc của lab.', noSuspended: 'Không có tài khoản nào đang bị khóa.', noSuspendedNote: 'Bảng này chỉ sáng lên khi một tài khoản bị chặn tạm thời hoặc vĩnh viễn khỏi luồng vận hành.', temporaryHold: 'Tạm khóa', permanentHold: 'Khóa vô thời hạn', restoreAccess: 'Khôi phục truy cập', blockReason: 'Lý do khóa', noReason: 'Chưa có lý do đính kèm.', restrictionWindow: 'Thời hạn hạn chế', restrictionNote: 'Tài khoản sẽ bị chặn cho đến khi nhóm vận hành gỡ cảnh báo.', approvalEyebrow: 'Áp lực phê duyệt', approvalCount: '{count} tài khoản đang chờ phê duyệt trước khi có thể gửi yêu cầu in.', filterPending: 'Lọc chờ duyệt', boardEyebrow: 'Bảng tài khoản', boardTitle: 'Sắp xếp quyền truy cập, quyền vai trò và trạng thái kiểm duyệt.', boardDesc: 'Tìm theo danh sách thành viên, thay đổi quyền nhân sự và xử lý tài khoản rủi ro mà không rời khỏi bảng.', visibleCount: '{count} đang hiển thị', suspendedCount: '{count} đang khóa', searchPlaceholder: 'Tìm tên, email hoặc mã sinh viên', allStatuses: 'Tất cả trạng thái', refresh: 'Làm mới bảng', loading: 'Đang tải bảng tài khoản...', noMatch: 'Không có tài khoản nào khớp với bộ lọc hiện tại.', noMatchNote: 'Hãy mở rộng từ khóa tìm kiếm hoặc đổi bộ lọc trạng thái kiểm duyệt.', noStudentId: 'Chưa có mã sinh viên', table: { user: 'Người dùng', contact: 'Liên hệ', joined: 'Tham gia', role: 'Vai trò', status: 'Trạng thái', actions: 'Tác vụ' }, mobileJoined: 'Ngày tạo', approve: 'Duyệt', suspend: 'Khóa', restore: 'Khôi phục', delete: 'Xóa', modalEyebrow: 'Tạm khóa kiểm duyệt', modalTitle: 'Tạm khóa {name}', modalDesc: 'Chọn thời hạn khóa, ghi lại lý do và giữ quyết định này luôn có thể truy vết cho các moderator khác.', timedHold: 'Khóa có thời hạn', timedHoldDesc: 'Tự động khôi phục quyền truy cập sau khoảng thời gian đã chọn.', permanentHoldDesc: 'Giữ tài khoản bị chặn cho đến khi nhân sự vận hành mở lại thủ công.', suspensionWindow: 'Thời hạn khóa', days: '{count} ngày', reason: 'Lý do', reasonPlaceholder: 'Mô tả vi phạm chính sách hoặc lý do kiểm duyệt...', cancel: 'Hủy', confirmSuspension: 'Xác nhận tạm khóa',
  },
  adminPricing: {
    heroEyebrow: 'Admin / Điều phối giá', heroTitle: 'Đặt các con số quyết định báo giá trước khi job bước vào sản xuất.', heroDesc: 'Điều chỉnh giá vật liệu, bật hoặc tắt phụ phí và xem ngay ảnh hưởng bằng bộ ước tính nhanh.', save: 'Lưu thay đổi bảng giá', saved: 'Đã lưu trạng thái bảng giá',
    stats: { pla: { label: 'Mốc PLA', note: 'Mức giá tham chiếu được dùng trong bộ ước tính nhanh bên dưới.' }, fees: { label: 'Phí đang bật', note: 'Các khoản phụ phí đang tham gia vào tổng chi phí.' } },
    materialEyebrow: 'Giá vật liệu', materialTitle: 'Đơn giá theo gram cho từng nhóm filament.', materialDesc: 'Mỗi thay đổi chỉ áp dụng cho những yêu cầu tạo sau thời điểm bạn lưu.', loadingMaterials: 'Đang tải bảng giá vật liệu...', futureRequests: 'Đơn giá cho các yêu cầu sắp tạo', vndPerGram: 'VND / gram', serviceEyebrow: 'Phí dịch vụ', serviceTitle: 'Phụ phí, chi phí xử lý và các công tắc vận hành.', serviceDesc: 'Bật, tắt hoặc điều chỉnh phụ phí mà không phải đụng vào giá nền của vật liệu.', loadingFees: 'Đang tải phụ phí dịch vụ...', feeLabels: { setup_fee: 'Phí khởi tạo job', rush_fee: 'Phí in nhanh', service_fee: 'Phí in hộ' }, feeDescriptions: { setup_fee: 'Áp dụng cho mỗi yêu cầu in cần qua quy trình tiếp nhận ban đầu.', rush_fee: 'Ưu tiên hàng đợi cho các yêu cầu cần xử lý sớm hơn bình thường.', service_fee: 'Phí dịch vụ in hộ tính theo gram vật liệu tiêu thụ.' }, perGram: 'Tính theo gram', enabled: 'Đang bật', disabled: 'Đang tắt', active: 'Đang hoạt động', inactive: 'Tạm tắt', flatFee: 'VND / lần', policyEyebrow: 'Chính sách giá', policyNote: 'Giá mới chỉ áp dụng cho các job được tạo sau khi bạn lưu. Job cũ giữ nguyên mức giá lúc được tạo.', estimatorEyebrow: 'Bộ ước tính nhanh', estimatorTitle: 'Kiểm tra ngay tác động của mức giá PLA hiện tại.', estimatorDesc: 'Bản xem nhanh này giúp bạn đối chiếu một mức báo giá nền trước khi áp dụng cho cả hàng đợi.', estimatorInput: 'Khối lượng vật liệu', estimatorTotal: 'Tổng PLA ước tính',
  },
  adminSettings: {
    success: 'Đã lưu cài đặt thành công.', loading: 'Đang tải cài đặt...', heroEyebrow: 'Admin / Cài đặt công khai', heroTitle: 'Điều chỉnh lớp thông tin sinh viên nhìn thấy trước khi họ cần hỗ trợ.', heroDesc: 'Những giá trị này đi vào landing page và các điểm chạm hỗ trợ, nên thông tin công khai luôn chính xác mà không cần sửa code.',
    stats: { channels: { label: 'Kênh hỗ trợ', value: '4', note: 'Email, Facebook, Zalo và đường dẫn hướng dẫn đều được quản lý từ bảng này.' }, publish: { label: 'Mô hình xuất bản', value: 'Đang áp dụng', note: 'Thay đổi được áp dụng qua admin API ngay khi bạn lưu cài đặt.' } },
    directoryEyebrow: 'Danh bạ hỗ trợ', directoryTitle: 'Các kênh liên hệ và hướng dẫn công khai.', directoryDesc: 'Để trống một trường nếu bạn không muốn kênh đó xuất hiện ở giao diện công khai.', supportEmail: 'Email hỗ trợ', supportEmailHint: 'Hộp thư chính để nhận các câu hỏi về lab và luồng vận hành.', facebookPage: 'Trang Facebook', facebookPageHint: 'Kênh công khai để cập nhật thông tin hoặc hướng dẫn đặt in.', zaloNumber: 'Số Zalo', zaloNumberHint: 'Kênh nhắn nhanh cho các câu hỏi ngắn hoặc việc theo dõi vận hành.', guideUrl: 'Đường dẫn hướng dẫn', guideUrlHint: 'Link tài liệu hoặc handbook cho người dùng mới.', saving: 'Đang lưu cài đặt...',
  },
  adminBackup: {
    heroEyebrow: 'Admin / Kho sao lưu', heroTitle: 'Giữ bản chụp hệ thống trong tầm tay trước khi khôi phục trở nên gấp gáp.', heroDesc: 'Tạo bản sao lưu thủ công, rà soát danh sách lưu trữ và tải đúng snapshot bạn muốn giữ ngoài hệ thống.', refresh: 'Làm mới sao lưu', create: 'Tạo bản sao lưu ngay', createdAlert: 'Đã tạo bản sao lưu: {file}',
    stats: { files: { label: 'Tệp sao lưu', note: 'Các snapshot hiện đang hiển thị trong thư mục sao lưu.' }, weight: { label: 'Dung lượng lưu trữ', note: 'Tổng dung lượng của toàn bộ gói sao lưu đang được liệt kê.' } },
    archiveEyebrow: 'Danh sách lưu trữ', archiveTitle: 'Rà soát từng snapshot trước khi xuất.', latestPrefix: 'Bản mới nhất: {date}.', noBackupsYet: 'Chưa có bản sao lưu nào.', filesCount: '{count} tệp', latestSize: '{size} gần nhất', loading: 'Đang tải kho sao lưu...', empty: 'Chưa có gói sao lưu nào.', emptyNote: 'Tạo một snapshot thủ công để chụp lại trạng thái hệ thống hiện tại trước khi bảo trì hoặc triển khai.', download: 'Tải xuống', retentionEyebrow: 'Ghi chú lưu trữ', retentionNote: 'Mỗi gói sao lưu đều chứa dữ liệu vận hành. Hãy lưu file tải xuống ở nơi được kiểm soát và tránh chia sẻ ra ngoài nhóm lab.',
  },
  adminOverview: {
    heroEyebrow: '// Bảng điều phối',
    heroTitle: 'Theo dõi nhịp Lab từ một bảng điều phối',
    heroDesc: 'Quan sát áp lực hàng đợi, khối lượng đơn cần duyệt và toàn bộ nhịp vận hành của đội máy in hiện tại.',
    historyEyebrow: '// Tra cứu lịch sử',
    historyTitle: 'Mỗi lệnh in, một dòng thời gian riêng.',
    historyDesc: 'Tìm theo tên file hoặc mã sinh viên để truy vết toàn bộ quá trình duyệt đơn, báo giá và sửa lỗi.',
    historySearchPlaceholder: 'Tìm kiếm yêu cầu',
    historyMatches: 'Số lệnh in khớp',
    historyEmptyTitle: 'Không có lệnh in nào lọt vào bộ lọc này.',
    historyEmptyDesc: 'Thử đổi trạng thái hoặc tìm theo từ khóa rộng hơn để tra cứu lại lịch sử.',
    viewHistory: 'Lịch sử lệnh in',
    viewArchive: 'Mở khu lưu trữ',
    userCardTitle: 'Tài khoản Lab',
    openRequestsTitle: 'Lệnh in lưu sổ',
    openRequestsNote: 'Các đơn in chưa trả xong hoặc chưa bị hủy.',
    attentionTitle: 'Gặp trục trặc',
    attentionNote: 'Cần liên hệ sinh viên để mài lại file, chốt lại.',
    needsRevisionEyebrow: '// Cần sinh viên sửa lại',
    needsRevisionTitle: '{count} đơn in kẹt lại, chờ sinh viên xác nhận và đổi file.',
    processingEyebrow: '// Tiến độ tổng',
    processingTitle: 'Toàn bộ lệnh đã nhận',
    actionsEyebrow: '// Nhiệm vụ',
    actionsTitle: 'Giải phóng hàng đợi nhanh.',
    actionsDesc: 'Xử lý báo giá, kiểm tra file và quyết định xem đơn nào sẽ được in tiếp theo.',
    shortcutsEyebrow: '// Truy cập tắt',
    trackingEyebrow: '// Theo dấu tiến độ',
    labStatsEyebrow: '// Thống kê tuần',
    sevenDayEyebrow: '// Nhịp điệu 7 ngày qua',
    quickQueueStatus: 'Theo dõi thứ tự chờ',
    metrics: {
      pending: { label: 'Đơn chờ giải quyết', note: 'Chưa chốt giá phí hoặc chưa lên lịch máy in' },
      total: { label: 'Tổng tải lệnh in', note: 'Số lượng đơn đang gom trong phạm vi này' },
      printing: { label: 'Đang chạy máy thật', note: 'Các khay nhựa đã ra khuôn' },
      done: { label: 'Đã trả hàng', note: 'Hàng đã in xong, Lab thu đủ phí' },
    },
    historyFilters: {
      all: 'Toàn bộ trạng thái kịch bản',
    },
    chartLegend: {
      done: 'Xong',
      approved: 'Đã duyệt',
      rejected: 'Đã báo hủy',
      revision: 'Bắt lỗi',
    },
    table: {
      request: 'Lệnh in đính kèm',
      printer: 'Tiến độ máy',
      material: 'Nguồn & Cuộn',
      status: 'Trạng thái hiện tại',
      open: 'Mở',
    },
    studentHeroTitle: 'Không bao giờ để mất tiến độ bản in.',
    studentHeroDesc: 'Lab theo dõi file, tự động báo rủi ro lỗi thiết kế, chốt mốc in mà không bỏ sót bất kì thay đổi nào từ phía bạn.',
    studentActionsTitle: 'Tạo một yêu cầu in mới ngay.',
    studentActionsDesc: 'Cấu hình chi phí, quăng file STL / 3MF vào và báo vị trí trong hàng chờ lập tức.',
    myRequestsEyebrow: '// Đơn in của mình',
    emptyStartDesc: 'Bắt đầu quăng file in đầu tiên của bạn vào hệ thống ngay thôi.',
  },
  moderatorQueue: {
    heroEyebrow: '// Chống kẹt hàng đợi',
    heroTitle: 'Giữ hàng đợi của Lab thông suốt, không kẹt cứng.',
    heroDesc: 'Xử lý các đơn chưa slice, phân tích thông số cuộn nhựa và đẩy file lên máy in. Mọi tương tác của bạn đều lập tức làm dịu hàng đợi.',
    cards: {
      pending: { label: 'Chờ Lab Xử Lý', note: 'Đơn mới nhảy vào hàng chờ, sinh viên đang háo hức đợi tin.' },
      printing: { label: 'Máy Đang Bận', note: 'File đã chạy và nhựa đang ra khỏi đầu phun.' },
      revision: { label: 'Cần Sửa Bù', note: 'Chờ sinh viên up lại file chuẩn để Mod xếp lịch tiếp.' },
    },
    listEyebrow: '// Danh sách các lệnh đang kẹt',
    listCount: '{count} lệnh in đang chờ xử lý tiến độ',
    refresh: 'Tải lại danh sách kẹt',
    searchPlaceholder: 'Tìm đơn',
    loading: 'Đang tổng hợp đơn kẹt...',
    emptyTitle: 'Hàng đợi đang thông thoáng kinh khủng.',
    emptyDesc: 'Không có đơn nào chưa được giải quyết khớp với bộ lọc Mod đang gõ.',
    selectTitle: 'Bấm một lệnh in bất kỳ để sửa file / báo giá lại.',
    selectDesc: 'Các bước thao tác đánh bật tiến độ hay đẩy file lên máy in sẽ nhảy ra tại đây.',
    profileEyebrow: '// Chân dung báo giá',
    requestedBy: 'Sinh viên tạo {user} · Bấm mã {id}',
    openDetail: 'Bật trang đầy đủ',
    statusQuickTitle: 'Nhảy mốc ưu tiên hỏa tốc',
    currentStatus: 'Thực trạng mốc này: {status}',
    changeTo: 'Ép chạy mốc...',
    summary: {
      material: 'Cuộn sẽ in',
      estimatedGrams: 'Mức tốn nhựa báo ban đầu',
      materialSource: 'Tiền đóng nhựa',
      estimatedTime: 'Thời lượng nằm trên máy tính toán',
    },
    quoteEyebrow: 'Chốt khối lượng thực sau Slice',
    quoteDesc: 'Quăng file stl để Slice trên Orca / Bambu của Lab. Lấy hao hụt Gram thực tế nhập vào để hệ thống tính lại tiền chính thức đưa học sinh.',
    quoteGrams: 'Khối lượng G-code thực',
    quoteCost: 'Dự trù thay đổi giá',
    quoteSaved: 'Đã úp mâm báo giá / Slice về cho sinh viên duyệt tiền.',
    quoteSave: 'Đóng giá mới sau Slice',
    printingEyebrow: '// Nhồi vào máy',
    printingMachine: 'Máy In Đảm Nhận: {name}',
    printingDesc: 'Hoàn tất bàn giao, móc cân để nhập lượng hao hụt kết thúc. Xoá mọi đơn kẹt cho máy này.',
    actualGrams: 'Đủ gram hao chưa?',
    actualGramsPlaceholder: 'Xong chốt số gram để trừ kho nhựa...',
    markDone: 'Trả hàng, dọn máy in',
    cancelJob: 'Hủy khẩn cấp đơn này',
    readyEyebrow: '// Sẵn sàng để lôi ra in',
    assignPrinter: 'Điều phối qua máy in',
    startPrinting: 'Tuyên bố: Có máy trống, bắt đầu in!',
    moderationEyebrow: '// Quản lý phê rủi ro thiết kế',
    approve: 'Báo sinh viên: File xịn, Tự In OK',
    requestRevision: 'Lỗi file nặng, bắt up file lại!',
    reject: 'Cấm in, rách việc',
    assignPrinterFirst: 'Phải móc vào cái máy in trước đã, rỗng kìa Mod!',
    revisionNoteAlert: 'Nói rõ bắt làm gì thì sinh viên mới sửa đổi được chứ Mod ơi!',
    moderatorNoteEyebrow: '// Lý do bắt sửa / Phê rủi ro',
    moderatorNotePlaceholder: 'Mô tả rõ vì sao file xấu, không khéo hỏng máy in, Support...?',
    noPrinter: 'Từ chối nhận gán',
    confirmStatus: 'Mod chắc sẽ chuyển nhanh "{from}" ép thành "{to}" không đấy?',
    actionError: 'Có biến...',
    updateError: 'Ghi xuống DB bị toạch!',
  },
  filePreview: {
    loading: 'Đang dựng preview lưới...',
    unavailable: 'Chưa bóc được bản dựng xem trước',
    threeDPreview: 'Xem Mô Hình 3D Ngay',
    threeMfThumbnail: 'Ảnh Render Kèm Từ 3MF',
  },
  chat: {
    eyebrow: '// Kênh xả giao',
    channelTitle: 'Kênh hỏi đáp xuyên Lab',
    channelDesc: 'Dùng chỗ này để hối Mod duyệt đơn cho lẹ, xin lời khuyên file đang lỗi hay hỏi han loại nhựa nào bền hơn cho đồ án của bạn.',
    autoRefresh: 'Tự thả tin mới nhảy về',
    every15s: 'Quét mỗi 15s',
    messages: 'Log tin nhắn',
    itemsVisible: '{count} tin đang nổi lên',
    refresh: 'Kéo tin mới',
    threadTitle: 'Luồng trao đổi chính',
    loadingMessages: 'Đang kéo các tin nhắn cũ lên...',
    noMessages: 'Phòng chat trống trơn. Thả một lời chào mở bát đi.',
    you: 'Bạn',
    roleBadgeAdmin: 'Trùm Lab',
    roleBadgeModerator: 'Mod Kê Đơn',
    roleBadgeStudent: 'Bạn in',
    attachJob: 'Đính kèm bản in',
    jobCodeLabel: 'Đính kèm để Mod dễ bắt mạch đơn đang hỏi',
    noJobAttached: 'Gắn link đơn: Không có',
    composeTitle: 'Gõ chữ...',
    composePlaceholder: 'Gõ lẹ cái vấn đề ra đây... (Enter để quăng, Shift+Enter xuống một dòng)',
    send: 'Quăng tin đi',
    sendNote: 'Tin nhắn sẽ public cho tất cả thành viên, Mod và Admin đang hóng trên hệ thống để bắt sóng hỗ trợ bạn lẹ nhất.',
  },
  jobDetail: {
    resubmitFailed: 'Gửi lại thất bại',
    tabOverview: 'Tổng quan',
    tabTimeline: 'Tiến độ',
    tabFiles: 'File in',
    tabPayment: 'Thanh toán',
    tabMessages: 'Tin nhắn',
    requestCodeLabel: 'Mã yêu cầu:',
    invoice: 'Hóa đơn',
    cancelConfirm: 'Bạn có chắc chắn muốn hủy yêu cầu in này không?',
    cancelSuccess: 'Yêu cầu đã được hủy thành công.',
    cancelFailed: 'Không thể hủy yêu cầu.',
    cancelRequest: 'Hủy yêu cầu',
    revisionTitle: 'Yêu cầu cần chỉnh sửa',
    revisionFallback: 'Bản in này cần điều chỉnh thêm, vui lòng liên hệ trực tiếp Moderator để biết thông tin nhé.',
    resubmitSuccess: 'Đã cập nhật file thành công. Yêu cầu đang được chờ duyệt lại.',
    resubmitButton: 'Gửi lại yêu cầu',
    detailTitle: 'Thông tin bổ sung',
    materialTypeLabel: 'Loại vật liệu',
    materialSourceLabel: 'Nguồn nhựa',
    estimatedWeightLabel: 'Khối lượng chốt',
    estimatedTimeLabel: 'Thời gian in dự kiến',
    assignedPrinterLabel: 'Máy in đảm nhận',
    notAssigned: 'Chưa gán',
    printSlotLabel: 'Khung giờ chạy máy',
    notScheduled: 'Chưa xếp lịch',
    printNotes: 'Ghi chú in ấn',
    noNotes: 'Không có ghi chú bổ sung nào.',
    paymentTitle: 'Chi phí & Thanh toán',
    paid: 'Đã thanh toán',
    unpaid: 'Chờ thanh toán',
    materialCost: 'Chi phí nhựa ({type})',
    serviceFee: 'Phí vận hành',
    total: 'Tổng thanh toán',
    paymentGuideTitle: 'Hướng dẫn thanh toán',
    paymentGuideDesc: 'Vui lòng thanh toán trực tiếp tại bàn trực Lab hoặc chuyển khoản theo mã QR bên dưới với nội dung bắt buộc bao gồm mã đơn và tên của bạn:',
    attachments: 'File thiết kế đính kèm',
    moderatorLabel: 'Moderator phụ trách',
    rejectionReason: 'Lý do từ chối',
  },
  queuePage: {
    noTime: 'Chưa báo mốc thời gian',
    cardQueueCount: 'Khối lượng hàng đợi',
    cardQueueNote: 'Toàn cảnh tất cả các lệnh in đang xếp hàng trong Lab.',
    cardMyJobs: 'Lệnh in của bạn',
    cardMyJobsHasNote: 'Hệ thống đã highlight các lệnh in do bạn gửi.',
    cardMyJobsEmptyNote: 'Bạn chưa có bản in nào nằm trong hàng chờ hiện tại.',
    cardReview: 'Chờ Check File',
    cardReviewNote: 'Đang kẹt ở khâu kiểm tra lỗi thiết kế hoặc xếp cấu hình in.',
    cardPrinting: 'Đang Chạy Máy',
    cardPrintingNote: 'Các sản phẩm đã lên khuôn và đang được in ấn.',
    heroEyebrow: '// Hàng đợi',
    heroTitle: 'Toàn cảnh các lệnh in đang xếp hàng.',
    heroDesc: 'Thứ tự trước sau và tiến độ thực tế của toàn bộ các yêu cầu được gửi tới Lab.',
    refreshQueue: 'Tải lại hàng đợi',
    myRequestsEyebrow: '// Yêu cầu của bạn',
    jobPosition: '{name} đang ở vị trí #{position}',
    highlightedNote: 'Đã bôi sáng để bạn dễ tìm đơn của mình',
    listEyebrow: '// Danh sách chờ',
    listTitle: 'Thứ tự ưu tiên xử lý',
    priorityNote: 'Xử lý tuần tự từ trên xuống dưới',
    loading: 'Đang cập nhật lại hàng đợi...',
    emptyTitle: 'Chưa dồn đơn nào vào hàng đợi.',
    emptyDesc: 'Danh sách này sẽ hiển thị thứ tự mốc xử lý ngay khi có ai đó gửi yêu cầu in mới.',
    yours: 'Của bạn',
    notScheduled: 'Chưa có lịch chạy',
    thPosition: 'Vị trí',
    thRequest: 'Yêu cầu',
    thSender: 'Người gửi',
    thMaterial: 'Vật liệu',
    thSlot: 'Ca / lịch',
    thStatus: 'Trạng thái',
    thSubmitted: 'Nộp lúc',
    rulesEyebrow: '// Nguyên tắc xếp hàng',
    rule1: 'Nộp sớm hơn sẽ đứng trước trong danh sách chờ.',
    rule2: 'Trạng thái được cập nhật ngay khi moderator duyệt hoặc đưa lệnh lên máy.',
    rule3: 'Các yêu cầu của bạn được tối đa được gửi đi 2 lần trong ngày.',
    statusesEyebrow: '// Trạng thái hiện có',
  },
  landing: {
    passwordMismatch: 'Mật khẩu xác nhận không khớp',
    confirmPassword: 'Xác nhận mật khẩu',
    passwordNotMatch: 'Mật khẩu không khớp',
    genericError: 'Có lỗi xảy ra',
    hidePassword: 'Ẩn mật khẩu',
    showPassword: 'Hiện mật khẩu',
  },
  colors: {
    white: 'Trắng', black: 'Đen', gray: 'Xám', blue: 'Xanh dương',
    green: 'Xanh lá', red: 'Đỏ', yellow: 'Vàng', orange: 'Cam',
    purple: 'Tím', pink: 'Hồng', other: 'Khác',
  },
    bookingWizard: {
    heroEyebrow: '// Gửi yêu cầu',
    heroTitle: 'Gửi yêu cầu in 3D mới',
    heroDesc: 'Chuẩn bị thông số, file thiết kế và lựa chọn lịch phù hợp trước khi đưa bản in vào hệ thống Lab.',
    currentStep: 'Tiến độ nhập',
    stepPrefix: 'Bước',
    printModeLabel: 'Hình thức đặt in',
    materialLabel: 'Chọn vật liệu',
    jobNameRequired: 'Bạn chưa nhập tên gọi cho bản in.',
    flowSelfLab: 'Tự in + Dùng Nhựa Lab: chọn loại nhựa → tải file gcode → đặt lịch → đến in & thanh toán nhựa.',
    flowSelfOwn: 'Tự in + Tự mang Nhựa: tải file thiết kế → đặt lịch → in hoàn toàn miễn phí.',
    flowLabLab: 'Nhờ Lab In hộ + Dùng Nhựa Lab: chọn loại nhựa → tải file thiết kế (STL) → chờ báo giá chi phí.',
    flowLabOwn: 'Nhờ Lab In hộ + Tự mang Nhựa: tải file thiết kế → chờ xếp lịch in hộ.',
    badgePaid: 'Mất phí',
    badgeFree: 'Miễn phí',
    labOk: 'Lab đồng ý',
    outOfStock: 'Đã cạn kho',
    noMaterialInStock: 'Cơ sở hiện không còn cuộn nhựa nào.',
    noColorForMaterial: 'Nhựa này hiện chưa có mã màu sẵn sàng.',
    multiColorLabel: 'Bản in {count} màu: {colors}',
    brandLabel: 'Dự định mang hãng nhựa gì? (Gợi ý)',
    brandHint: 'Nếu có, Lab sẽ chuẩn bị cấu hình tốt nhất cho hãng nhựa này.',
    costStructure: 'Chi phí tính toán:',
    materialFeeLabel: 'Chi phí Nhựa',
    materialFeeDesc: 'Lượng nhựa hao hụt × đơn giá của Lab',
    serviceFeeLabel: 'Phí vận hành hộ',
    serviceFeeDesc: 'Áp dụng đối với hình thức "In hộ"',
    notApplicable: 'Không tính',
    caseSelfOwn: 'Tự in + tự đóng góp nhựa: Lab không thu phí nào.',
    caseSelfLab: 'Tự in + mượn nhựa Lab: Chỉ thu phí lượng vật liệu hao hụt.',
    noServiceFee: 'Bạn sẽ tự vận hành nên không tính phí dịch vụ.',
    caseLabOwn: 'In hộ + dự kiến tự mang nhựa: Lab chỉ thu phí mài mòn và thao tác máy.',
    freeMaterialNote: 'Miễn trừ tiền vật liệu in.',
    caseLabLab: 'In hộ + dùng nhựa Lab: Tính đủ phí nhựa và vận hành.',
    costFinalNote: 'Trình quản lý sẽ báo lại giá nét cho bạn sau bước tự Slice khối lượng thực tế.',
    uploadLabNote: 'Upload file STL hoặc 3MF — Lab sẽ tự slice và xếp lịch in cho bạn. Không cần slice trước.',
    uploadGcodeLabel: 'Tải lên File (.gcode / .gcode.3mf)',
    uploading: 'Đang tải lên...',
    supportGcode: 'Hỗ trợ .gcode, .gcode.3mf (tối đa 50MB)',
    autoCalc: 'Tự động tính toán từ file đã slice',
    exampleGrams: 'Ví dụ: 45',
    materialCostLabel: 'Vật liệu',
    serviceCostLabel: 'Phí in hộ',
    totalEstimate: 'Tổng ước tính',
    modConfirmAfterSlice: 'Ước tính — Mod xác nhận sau khi slice',
    freeTotal: '0đ — Miễn phí',
    ownMaterialFreeNote: 'Tự mang nhựa không tính phí vật liệu',
    printerSkipNote: 'Bỏ qua nếu chưa biết — Moderator sẽ xếp máy phù hợp.',
    subSlotLabel: 'Khung giờ ưu tiên trong ca (recommend)',
    subSlotHint: 'Tùy chọn — Moderator sẽ xác nhận lịch cụ thể.',
    noteLabel: 'Lưu ý',
    reviewFormLabel: 'Hình thức',
    reviewOwnFree: 'Tự mang nhựa — miễn phí',
    reviewTotal: 'Tổng',
    submitHint: 'Kiểm tra lại thông tin trước khi gửi vào hàng chờ.',
    editHint: 'Bạn có thể quay lại bước trước để chỉnh lại thông tin.',
    fileErrorGcode: 'Chỉ hỗ trợ .gcode và .gcode.3mf (file đã slice từ Bambu/Orca)',
    fileErrorStl: 'Chỉ hỗ trợ file chưa slice (.stl, .3mf). Không up file .gcode hoặc .gcode.3mf ở chế độ này',
    uploadFailed: 'Upload thất bại',
    submitFailed: 'Gửi yêu cầu thất bại',
    confirmTermsError: 'Vui lòng xác nhận điều khoản trước khi gửi.',
  },
} as const;

const jpOverrides = {
  shared: {
    loadingWorkspace: 'Loading workspace', userLabel: 'User', statusLabel: 'Status', statusOnline: 'Lab online', refresh: 'Refresh', languageLabel: 'Language', languageToggle: 'Switch language', languageNames: { VN: 'Vietnamese', JP: 'English' }, themeLabel: 'Theme', themeToggle: 'Switch theme', themeLight: 'Light mode', themeDark: 'Dark mode', openNavigation: 'Open navigation', closeNavigation: 'Close navigation', closeOverlay: 'Close navigation overlay', backDashboard: 'Back to overview', systemUser: 'System user', pageUnavailable: 'This page is still being polished.', pageLoadFailed: 'Unable to load this request.', jobDetailSelectedNote: 'Review request {id} together with the related operation notes.', noDate: 'No date', noDuration: 'No duration yet', notAssigned: 'Unassigned', waitingApproval: 'Pending review', createdOn: 'Created on {date}', openItem: 'Open {name}', choosePrinter: 'Choose a printer', jobStatuses: { Draft: 'Draft', Submitted: 'Submitted', 'Pending review': 'Pending review', Approved: 'Approved', Scheduled: 'Scheduled', Printing: 'Printing', Done: 'Done', Rejected: 'Rejected', Cancelled: 'Cancelled', 'Needs Revision': 'Needs revision' }, materialSources: { Personal: 'Personal supply', Lab: 'Lab stock' },
    save: 'Save'
  },
  pageMeta: {
    dashboard: { eyebrow: '// Workspace', title: 'Operations overview', note: 'Track requests, review load and manage material state.' },
    booking: { eyebrow: '// New request', title: 'New print request', note: 'Prepare file, material and notes before the request enters the review queue.' },
    history: { eyebrow: '// Archive', title: 'Request history', note: 'Review sent requests, scheduling decisions and completed prints.' },
    queue: { eyebrow: '// Moderation', title: 'Review queue', note: 'Approve, request revisions and balance the current queue.' },
    inventory: { eyebrow: '// Materials', title: 'Material stock', note: 'Track stock, available colors and warning thresholds.' },
    analytics: { eyebrow: '// Pricing', title: 'Pricing controls', note: 'Adjust material rates, service fees and quote references.' },
    users: { eyebrow: '// Access', title: 'User roster', note: 'Manage student accounts, staff roles and moderation status.' },
    printers: { eyebrow: '// Printers', title: 'Printer operations', note: 'Keep readiness, fleet state and printer details in sync.' },
    chat: { eyebrow: '// Messaging', title: 'Lab conversation', note: 'Keep students and operators in the same thread.' },
    backup: { eyebrow: '// Backups', title: 'System backups', note: 'Protect runtime data, exported files and recovery checkpoints.' },
    settings: { eyebrow: '// Settings', title: 'Lab settings', note: 'Adjust defaults, contact channels and operational rules.' },
    pricing: { eyebrow: '// Public', title: 'Pricing overview', note: 'Show students a clean reference for materials, surcharges and print cost.' },
    'queue-status': { eyebrow: '// Queue', title: 'Queue status', note: 'Inspect current load, upcoming work and request order.' },
    'job-detail': { eyebrow: '// Detail', title: 'Request detail', note: 'Inspect files, notes and the processing trail of one request.' },
  },
  sidebar: { mobileEyebrow: '// Navigation', mobileTitle: 'Operations web', brandEyebrow: '// 3D print room', brandTitle: 'Operations web', brandNote: 'Track requests, review the queue and keep printer and material state aligned.', sectionLabel: '// Workspace', logout: 'Log out', nav: { dashboard: 'Overview', booking: 'Create request', history: 'Request history', pricing: 'Pricing', 'queue-status': 'Queue', queue: 'Review queue', printers: 'Printers', inventory: 'Materials', users: 'Users', analytics: 'Pricing & fees', backup: 'Backups', settings: 'Settings', chat: 'Messages' } },
  roles: { studentSpace: 'Student workspace', moderatorSpace: 'Operations web', adminSpace: 'Administrator', sidebarStudent: 'Student workspace', sidebarModerator: 'Review desk', sidebarAdmin: 'Operations admin', admin: 'Admin', moderator: 'Moderator', student: 'Student' },
  adminPrinters: {
    heroEyebrow: '// Printers',
    heroTitle: 'Track capacity, printer state and campus allocation from one board.',
    heroDesc: 'Group machines by campus, update live operating state and keep image and material profiles aligned with the real fleet.',
    refresh: 'Refresh fleet',
    add: 'Add printer',
    loading: 'Loading printer fleet...',
    empty: 'No printers have been configured yet.',
    createFirst: 'Create the first printer',
    stats: {
      fleet: { label: 'Fleet size', note: 'Every printer currently tracked by the system.' },
      available: { label: 'Ready now', note: 'Printers that can receive new jobs immediately.' },
      ams: { label: 'AMS ready', note: 'Machines that support material switching or multi-color prints.' },
      busy: { label: 'Busy now', note: 'Printers currently printing or reserved for active jobs.' },
    },
    campusLabel: 'Campus',
    campusNote: '{count} printers are currently managed in this campus zone.',
    campusTotal: '{count} total',
    campusAvailable: '{count} ready',
    profile: 'Printer profile',
    supportedMaterials: 'Supported materials',
    campusField: 'Campus',
    campusFieldNote: 'Update the state as soon as a printer becomes busy or enters maintenance.',
    edit: 'Edit',
    statusAvailable: 'Available',
    statusBusy: 'Busy',
    statusMaintenance: 'Maintenance',
    deleteConfirm: 'Delete printer "{name}"? This action cannot be undone.',
    validationName: 'Please enter the printer name and build volume.',
    validationMaterial: 'Please choose at least one supported material.',
    modalEyebrow: '// Printer profile',
    modalEditTitle: 'Edit printer profile',
    modalAddTitle: 'Add a new printer',
    modalDesc: 'Keep image, supported materials and operating state aligned with the real machine.',
    preview: 'Preview',
    uploadImage: 'Upload printer image',
    imageUrlPlaceholder: 'Or paste an image URL',
    printerName: 'Printer name',
    printerNamePlaceholder: 'Bambu Lab A1 / Ender 3 / X1 Carbon',
    buildVolume: 'Build volume',
    buildVolumePlaceholder: '256 x 256 x 256 mm',
    selectCampus: 'Campus',
    customCampusPlaceholder: 'Custom campus label',
    selectMaterials: 'Supported materials',
    hasAms: 'AMS support',
    hasAmsDesc: 'Use this for printers that can hold multiple reels or switch material and color automatically.',
    statusField: 'Operating status',
    cancel: 'Cancel',
    saveAdd: 'Create printer',
    saveEdit: 'Save changes',
  },
  adminInventory: {
    heroEyebrow: '// Materials',
    heroTitle: 'Track every reel before the queue hits a shortage threshold.',
    heroDesc: 'Keep stock state by campus, update grams in real time and spot bottlenecks before operators run out of material mid-shift.',
    refresh: 'Refresh stock',
    add: 'Add material reel',
    closeAdd: 'Close intake form',
    loading: 'Loading material stock...',
    stats: {
      pla: { label: 'PLA stock', note: 'PLA available for common student requests.' },
      petg: { label: 'PETG stock', note: 'Stock reserved for jobs needing more strength or heat resistance.' },
      low: { label: 'Needs refill', note: 'Reels that are low or empty and should be replenished.' },
      tracked: { label: 'Tracked reels', note: 'Total number of reels monitored across campuses.' },
    },
    deleteConfirm: 'Remove this material reel from stock?',
    newEyebrow: '// New reel',
    newTitle: 'Record a new material reel in the stock board.',
    newDesc: 'Capture campus, material, color, brand and warning threshold in one pass so the whole team sees the same inventory state.',
    requiredHint: 'Required: material + color',
    area: 'Campus',
    material: 'Material',
    brand: 'Brand',
    brandPlaceholder: 'Bambu, eSUN, Elegoo...',
    location: 'Storage location',
    locationPlaceholder: 'Shelf A1 / Level 2',
    color: 'Color',
    selectPresetColor: 'Choose a preset color',
    customColor: 'Custom color',
    customColorPlaceholder: 'Enter a custom color name',
    remainingGrams: 'Current weight (g)',
    threshold: 'Warning threshold (g)',
    saveReel: 'Save material reel',
    collapseForm: 'Collapse form',
    boardEyebrow: '// Stock board',
    boardTitle: 'Read stock by campus and update only what changed.',
    boardDesc: 'Search by reel ID, material, brand or color so everyone works from the same stock view.',
    visibleCount: '{count} visible reels',
    reviewCount: '{count} need review',
    searchPlaceholder: 'Search reel ID, material, color or brand',
    areaEyebrow: 'Material shelf',
    areaNote: '{count} reels are currently managed in this campus zone.',
    areaCount: '{count} reels',
    lowCount: '{count} low',
    emptyArea: 'No reels are registered in this campus zone yet.',
    noBrand: 'No brand',
    noShelf: 'No shelf',
    updateStock: 'Update stock',
    deleteReel: 'Delete reel',
    stockRemaining: '{count}g left',
    stockThreshold: 'Threshold {count}g',
    inStock: 'In stock',
    lowStock: 'Low',
    outOfStock: 'Out of stock',
    reelId: 'Reel ID',
    actions: 'Actions',
    disciplineEyebrow: 'Stock discipline',
    disciplineNote: 'Low-stock reels should be reviewed before they get assigned to a new print run.',
  },
  adminUsers: {
    noDate: 'No date',
    permanent: 'Permanent',
    heroEyebrow: 'Admin / User governance',
    heroTitle: 'Shape access before an account reaches the lab floor.',
    heroDesc: 'Review registrations, switch role responsibility and keep risky accounts outside the printer flow.',
    tabs: { users: 'Account board', warnings: 'Suspension board' },
    stats: {
      total: { label: 'Accounts in system', note: 'Every student and operator account currently registered.' },
      active: { label: 'Active access', note: 'Members who can currently use the lab flow.' },
      pending: { label: 'Pending review', note: 'Accounts waiting for manual approval.' },
      staff: { label: 'Lab staff roles', note: 'Admin and moderator seats currently in circulation.' },
    },
    roleLabels: { Admin: 'Admin', Moderator: 'Moderator', Student: 'Student' },
    statusLabels: { active: 'Active', pending: 'Pending', suspended: 'Suspended' },
    deleteConfirm: 'Delete account "{name}"? This cannot be undone and will remove related print requests.',
    riskEyebrow: 'Risk board',
    riskCount: '{count} accounts are currently blocked from the lab flow.',
    noSuspended: 'No suspended accounts.',
    noSuspendedNote: 'This board lights up only when an account has been temporarily or permanently removed from the workflow.',
    temporaryHold: 'Temporary hold',
    permanentHold: 'Permanent hold',
    restoreAccess: 'Restore access',
    blockReason: 'Block reason',
    noReason: 'No reason attached.',
    restrictionWindow: 'Restriction window',
    restrictionNote: 'The account stays unavailable until staff clears the warning.',
    approvalEyebrow: 'Approval pressure',
    approvalCount: '{count} accounts are waiting for approval before they can submit jobs.',
    filterPending: 'Filter pending',
    boardEyebrow: 'Account board',
    boardTitle: 'Sort access, role ownership and moderation state.',
    boardDesc: 'Search the roster, promote staff roles and action risky accounts without leaving the board.',
    visibleCount: '{count} visible',
    suspendedCount: '{count} suspended',
    searchPlaceholder: 'Search name, email or student ID',
    allStatuses: 'All statuses',
    refresh: 'Refresh board',
    loading: 'Loading account board...',
    noMatch: 'No accounts match the current filter.',
    noMatchNote: 'Try widening the search or changing the moderation status filter.',
    noStudentId: 'No student ID',
    table: { user: 'User', contact: 'Contact', joined: 'Joined', role: 'Role', status: 'Status', actions: 'Actions' },
    mobileJoined: 'Joined',
    approve: 'Approve',
    suspend: 'Suspend',
    restore: 'Restore',
    delete: 'Delete',
    modalEyebrow: 'Moderation hold',
    modalTitle: 'Suspend {name}',
    modalDesc: 'Choose a suspension window, log the reason and keep the decision traceable for other moderators.',
    timedHold: 'Timed hold',
    timedHoldDesc: 'Restore access automatically after the chosen window.',
    permanentHoldDesc: 'Keep the account blocked until staff restores it manually.',
    suspensionWindow: 'Suspension window',
    days: '{count} days',
    reason: 'Reason',
    reasonPlaceholder: 'Describe the policy breach or moderation reason...',
    cancel: 'Cancel',
    confirmSuspension: 'Confirm suspension',
  },
  adminPricing: {
    heroEyebrow: 'Admin / Pricing control',
    heroTitle: 'Set the numbers that define every quote before a job hits production.',
    heroDesc: 'Tune material prices, enable or disable surcharges and preview the effect immediately with a lightweight estimator.',
    save: 'Save pricing changes',
    saved: 'Saved pricing state',
    stats: {
      pla: { label: 'PLA baseline', note: 'The reference price used in the quick estimator below.' },
      fees: { label: 'Active fees', note: 'Service charges currently contributing to the total.' },
    },
    materialEyebrow: 'Material pricing',
    materialTitle: 'Per-gram pricing by filament family.',
    materialDesc: 'Each rate updates future requests only. Existing jobs keep the price they were created with.',
    loadingMaterials: 'Loading material pricing...',
    futureRequests: 'Filament pricing for future requests',
    vndPerGram: 'VND / gram',
    serviceEyebrow: 'Service fees',
    serviceTitle: 'Surcharges, handling costs and operational toggles.',
    serviceDesc: 'Enable, disable or adjust fees without touching the material baseline.',
    loadingFees: 'Loading service fees...',
    feeLabels: {
      setup_fee: 'Job setup fee',
      rush_fee: 'Rush fee',
      service_fee: 'Operator assist fee',
    },
    feeDescriptions: {
      setup_fee: 'Applies to each request entering intake.',
      rush_fee: 'Prioritizes a request in the queue.',
      service_fee: 'Charged per gram of consumed material.',
    },
    perGram: 'Per gram',
    enabled: 'Enabled',
    disabled: 'Disabled',
    active: 'Active',
    inactive: 'Inactive',
    flatFee: 'VND flat fee',
    policyEyebrow: 'Pricing policy',
    policyNote: 'New prices apply only to jobs created after you save the board. Historical jobs keep their original numbers.',
    estimatorEyebrow: 'Quick estimator',
    estimatorTitle: 'Check the immediate effect of the current PLA pricing.',
    estimatorDesc: 'This preview helps you sanity-check a baseline quote before pushing changes to the whole queue.',
    estimatorInput: 'Material grams',
    estimatorTotal: 'Estimated PLA total',
  },
  adminSettings: {
    success: 'Settings saved successfully.',
    loading: 'Loading settings...',
    heroEyebrow: 'Admin / Public settings',
    heroTitle: 'Shape the contact layer students see before they ask for help.',
    heroDesc: 'These values feed the landing page and support touchpoints, so the public guidance stays accurate without touching code.',
    stats: {
      channels: { label: 'Support channels', value: '4', note: 'Email, Facebook, Zalo and guide URL are all managed from this board.' },
      publish: { label: 'Publishing model', value: 'Live', note: 'Changes are applied through the admin API as soon as you save.' },
    },
    directoryEyebrow: 'Support directory',
    directoryTitle: 'Contact channels and public guidance.',
    directoryDesc: 'Leave a field empty if you do not want that channel to appear publicly.',
    supportEmail: 'Support email',
    supportEmailHint: 'Primary inbox for lab support and workflow questions.',
    facebookPage: 'Facebook page',
    facebookPageHint: 'Public social channel for updates or booking guidance.',
    zaloNumber: 'Zalo number',
    zaloNumberHint: 'Fast messaging channel for short questions or operational follow-up.',
    guideUrl: 'Guide URL',
    guideUrlHint: 'Documentation or handbook link for first-time users.',
    saving: 'Saving settings...',
  },
  adminBackup: {
    heroEyebrow: 'Admin / Backup vault',
    heroTitle: 'Keep recovery snapshots close before restoration becomes urgent.',
    heroDesc: 'Create manual backups, review the archive list and download the exact snapshot you want to store outside the system.',
    refresh: 'Refresh backups',
    create: 'Create backup now',
    createdAlert: 'Backup created: {file}',
    stats: {
      files: { label: 'Backup files', note: 'Snapshots currently visible in the backup directory.' },
      weight: { label: 'Storage weight', note: 'Total size of the backup packages currently listed.' },
    },
    archiveEyebrow: 'Archive list',
    archiveTitle: 'Review each snapshot before export.',
    latestPrefix: 'Latest snapshot: {date}.',
    noBackupsYet: 'No backups yet.',
    filesCount: '{count} files',
    latestSize: '{size} latest',
    loading: 'Loading backup inventory...',
    empty: 'No backup archives yet.',
    emptyNote: 'Create a snapshot before maintenance or deployment.',
    download: 'Download',
    retentionEyebrow: 'Retention note',
    retentionNote: 'Each archive contains production data. Store exported files securely.',
  },
  adminOverview: { heroEyebrow: '// Control board', heroTitle: 'Operations overview', heroDesc: 'Watch queue pressure, review load and printer rhythm from one control surface.', historyEyebrow: '// Archive', historyTitle: 'Every request, one timeline.', historyDesc: 'Search by request name or ID, then filter by status to review the full processing trail.', historySearchPlaceholder: 'Search requests', historyMatches: 'Matching requests', historyEmptyTitle: 'No requests match the current filters.', historyEmptyDesc: 'Try a different status or search term to widen the archive results.', viewHistory: 'View history', viewArchive: 'View archive', userCardTitle: 'User', openRequestsTitle: 'Open requests', openRequestsNote: 'Requests still moving through the workflow.', attentionTitle: 'Needs attention', attentionNote: 'Requests waiting for updated files or notes.', needsRevisionEyebrow: '// Needs revision', needsRevisionTitle: '{count} requests need updates before printing.', processingEyebrow: '// In progress', processingTitle: 'All requests', actionsEyebrow: '// Actions', actionsTitle: 'Review the queue.', actionsDesc: 'Adjust and schedule print work.', shortcutsEyebrow: '// Shortcuts', trackingEyebrow: '// Status tracking', labStatsEyebrow: '// Lab stats', sevenDayEyebrow: '// 7-day pulse', quickQueueStatus: 'Queue status', metrics: { pending: { label: 'Pending requests', note: 'Waiting for review or scheduling' }, total: { label: 'Total requests', note: 'All requests in the current scope' }, printing: { label: 'Printing', note: 'Currently running on machines' }, done: { label: 'Completed', note: 'Finished and recorded' } }, historyFilters: { all: 'All statuses' }, chartLegend: { done: 'Done', approved: 'Approved', rejected: 'Rejected', revision: 'Revision' }, table: { request: 'Request', printer: 'Printer', material: 'Material', status: 'Status', open: 'Open' }, studentHeroTitle: 'Keep every print request on track.', studentHeroDesc: 'Track files, approvals and print schedules without missing progress on any request.', studentActionsTitle: 'Create a new print request.', studentActionsDesc: 'Set up a request, attach files and put the job into the review pipeline with clear details from the start.', myRequestsEyebrow: '// My requests', emptyStartDesc: 'Create your first print request to start filling this workspace.' },
  moderatorQueue: { heroEyebrow: '// Review queue', heroTitle: 'Keep moderation crisp, visible and unblocked.', heroDesc: 'Find the next request to process, inspect material details quickly and act from the same workstation. Every state change flows straight back into the queue.', cards: { pending: { label: 'Pending review', note: 'Requests waiting for a moderation decision before scheduling.' }, printing: { label: 'Printing', note: 'Jobs already assigned to a machine and currently running.' }, revision: { label: 'Needs revision', note: 'Requests waiting for students to update files or notes.' } }, listEyebrow: '// Requests to process', listCount: '{count} open requests', refresh: 'Refresh', searchPlaceholder: 'Search by request name, sender or job ID', loading: 'Loading queue...', emptyTitle: 'No requests match the current filters.', emptyDesc: 'Try a different search term or refresh the list to pull the latest data.', selectTitle: 'Choose a request to inspect.', selectDesc: 'Once you select a job on the left, all moderation details and operating controls appear here.', profileEyebrow: '// Request profile', requestedBy: 'Requested by {user} · {id}', openDetail: 'Open detail', statusQuickTitle: 'Quick status switch', currentStatus: 'Current status: {status}', changeTo: 'Change to...', summary: { material: 'Material', estimatedGrams: 'Estimated weight', materialSource: 'Material source', estimatedTime: 'Estimated duration' }, quoteEyebrow: 'Requote', quoteDesc: 'After slicing the file, enter the actual material estimate so the system can recalculate the quote for the student.', quoteGrams: 'New gram estimate', quoteCost: 'Projected cost', quoteSaved: 'Quote updated successfully.', quoteSave: 'Save new quote', printingEyebrow: '// Printing', printingMachine: 'Printer: {name}', printingDesc: 'When the job finishes, enter the actual grams and mark it complete.', actualGrams: 'Actual grams', actualGramsPlaceholder: 'Enter after printing finishes', markDone: 'Mark complete', cancelJob: 'Cancel job', readyEyebrow: '// Ready to print', assignPrinter: 'Assign printer', startPrinting: 'Start printing', moderationEyebrow: '// Moderation actions', approve: 'Approve', requestRevision: 'Request revision', reject: 'Reject', assignPrinterFirst: 'Assign a printer first', revisionNoteAlert: 'Enter the revision request in the moderator notes field first.', moderatorNoteEyebrow: '// Moderator notes', moderatorNotePlaceholder: 'Add the rejection reason or the changes the student needs to make...', noPrinter: 'Not assigned', confirmStatus: 'Change status from "{from}" to "{to}"?', actionError: 'Something went wrong.', updateError: 'Update failed.' },
  filePreview: {
    loading: 'Loading preview...',
    unavailable: 'Preview unavailable',
    threeDPreview: '3D Preview',
    threeMfThumbnail: '3MF Thumbnail',
  },
  chat: {
    eyebrow: '// Messaging',
    channelTitle: 'Lab messaging channel',
    channelDesc: 'Use this section to ask about order status, remind moderators to review files or discuss print request adjustments.',
    autoRefresh: 'Auto refresh',
    every15s: 'Every 15 seconds',
    messages: 'Messages',
    itemsVisible: '{count} items visible',
    refresh: 'Refresh',
    threadTitle: 'Conversation thread',
    loadingMessages: 'Loading messages...',
    noMessages: 'No messages yet. You can start the conversation.',
    you: 'You',
    roleBadgeAdmin: 'Admin',
    roleBadgeModerator: 'Moderator',
    roleBadgeStudent: 'Student',
    attachJob: 'Attach to job',
    jobCodeLabel: 'Reference by job ID',
    noJobAttached: 'No specific job attached',
    composeTitle: 'Compose message',
    composePlaceholder: 'Type your message... Enter to send, Shift + Enter for new line.',
    send: 'Send message',
    sendNote: 'Your message will be visible to students, moderators and admins with system access.',
  },
  jobDetail: {
    resubmitFailed: 'Resubmit failed',
    tabOverview: 'Overview',
    tabTimeline: 'Timeline',
    tabFiles: 'Print files',
    tabPayment: 'Payment',
    tabMessages: 'Messages',
    requestCodeLabel: 'Request code:',
    invoice: 'Invoice',
    cancelConfirm: 'Are you sure you want to cancel this request?',
    cancelSuccess: 'Request cancelled successfully.',
    cancelFailed: 'Failed to cancel request',
    cancelRequest: 'Cancel request',
    revisionTitle: 'Moderator requested revision',
    revisionFallback: 'Please contact the Moderator for more details.',
    resubmitSuccess: 'Resubmitted successfully. Awaiting re-review.',
    resubmitButton: 'Resubmit request',
    detailTitle: 'Request details',
    materialTypeLabel: 'Material type',
    materialSourceLabel: 'Material source',
    estimatedWeightLabel: 'Estimated weight',
    estimatedTimeLabel: 'Estimated print time',
    assignedPrinterLabel: 'Assigned printer',
    notAssigned: 'Not assigned',
    printSlotLabel: 'Print slot',
    notScheduled: 'Not scheduled',
    printNotes: 'Print notes',
    noNotes: 'No notes.',
    paymentTitle: 'Payment details',
    paid: 'Paid',
    unpaid: 'Pending payment',
    materialCost: 'Material cost ({type})',
    serviceFee: 'Service fee',
    total: 'Total',
    paymentGuideTitle: 'Payment instructions',
    paymentGuideDesc: 'Please pay at the Lab front desk or transfer via the QR code below with the reference:',
    attachments: 'Attachments',
    moderatorLabel: 'Assigned moderator',
    rejectionReason: 'Rejection reason',
  },
  queuePage: {
    noTime: 'No time available',
    cardQueueCount: 'Jobs in queue',
    cardQueueNote: 'All requests currently present in the print queue.',
    cardMyJobs: 'Your jobs',
    cardMyJobsHasNote: 'Your requests are highlighted throughout the list.',
    cardMyJobsEmptyNote: 'You have no requests in the current queue.',
    cardReview: 'Pending review',
    cardReviewNote: 'Requests awaiting moderator review before scheduling.',
    cardPrinting: 'Printing',
    cardPrintingNote: 'Jobs currently running on printers.',
    heroEyebrow: '// Queue',
    heroTitle: 'See where each request stands in the queue.',
    heroDesc: 'This list reflects the current processing order. Earlier submissions rank higher, and statuses show which step each job is at.',
    refreshQueue: 'Refresh queue',
    myRequestsEyebrow: '// Your requests',
    jobPosition: '{name} at position #{position}',
    highlightedNote: 'Your rows are highlighted for quick tracking',
    listEyebrow: '// Queue list',
    listTitle: 'Current processing order',
    priorityNote: 'Priority from top to bottom',
    loading: 'Loading queue...',
    emptyTitle: 'There are no requests in the queue yet.',
    emptyDesc: 'When new requests enter the processing pipeline, this list will show the corresponding queue order.',
    yours: 'Yours',
    notScheduled: 'Not scheduled',
    thPosition: 'Position',
    thRequest: 'Request',
    thSender: 'Sender',
    thMaterial: 'Material',
    thSlot: 'Slot / schedule',
    thStatus: 'Status',
    thSubmitted: 'Submitted',
    rulesEyebrow: '// Queue rules',
    rule1: 'Earlier submissions are placed higher in the queue.',
    rule2: 'Status updates as soon as a moderator approves or assigns a job to a printer.',
    rule3: 'Your requests are always highlighted for quick tracking.',
    statusesEyebrow: '// Available statuses',
  },
  landing: {
    passwordMismatch: 'Passwords do not match',
    confirmPassword: 'Confirm password',
    passwordNotMatch: 'Passwords do not match',
    genericError: 'Something went wrong',
    hidePassword: 'Hide password',
    showPassword: 'Show password',
  },
  colors: {
    white: 'White', black: 'Black', gray: 'Gray', blue: 'Blue',
    green: 'Green', red: 'Red', yellow: 'Yellow', orange: 'Orange',
    purple: 'Purple', pink: 'Pink', other: 'Other',
  },
  bookingWizard: {
    heroEyebrow: '// Book print',
    heroTitle: 'Submit a 3D print request',
    heroDesc: 'Complete each step to select print mode, material, file and preferred schedule before adding the request to the queue.',
    currentStep: 'Current step',
    stepPrefix: 'Step',
    printModeLabel: 'Mode',
    materialLabel: 'Material',
    jobNameRequired: 'Request name is required',
    flowSelfLab: 'Self print + Lab material: pick material → upload .gcode/.gcode.3mf → choose printer & time → confirm (charged)',
    flowSelfOwn: 'Self print + Own material: upload STL/3MF → choose printer & time → confirm (free)',
    flowLabLab: 'Operator assist + Lab material: pick material → upload STL/3MF → wait for Mod quote',
    flowLabOwn: 'Operator assist + Own material: pick material → upload STL/3MF → wait for Mod scheduling (free)',
    badgePaid: 'Charged',
    badgeFree: 'Free',
    labOk: 'Lab ok ✓',
    outOfStock: 'Out of stock',
    noMaterialInStock: 'No material currently in stock.',
    noColorForMaterial: 'No colors available for this material type.',
    multiColorLabel: 'Printing {count} colors: {colors}',
    brandLabel: 'Filament brand (recommended)',
    brandHint: 'The brand you will bring to the lab',
    costStructure: 'Cost structure',
    materialFeeLabel: 'Material fee (Lab)',
    materialFeeDesc: 'Lab filament × unit price',
    serviceFeeLabel: 'Service fee (Lab operated)',
    serviceFeeDesc: 'Applies when "Operator assist" is selected',
    notApplicable: 'Not applicable',
    caseSelfOwn: 'Self print + Own material: Completely free',
    caseSelfLab: 'Self print + Lab material: Pay for filament',
    noServiceFee: 'No service fee.',
    caseLabOwn: 'Operator assist + Own material: Only pay service fee',
    freeMaterialNote: 'Free material.',
    caseLabLab: 'Operator assist + Lab material: Material',
    costFinalNote: 'Final cost is based on actual grams at the next step.',
    uploadLabNote: 'Upload STL or 3MF — the lab will slice and schedule the print for you. No need to slice first.',
    uploadGcodeLabel: 'Upload file (.gcode / .gcode.3mf)',
    uploading: 'Uploading...',
    supportGcode: 'Supports .gcode, .gcode.3mf (max 50MB)',
    autoCalc: 'Auto-calculated from sliced file',
    exampleGrams: 'e.g. 45',
    materialCostLabel: 'Material',
    serviceCostLabel: 'Service fee',
    totalEstimate: 'Estimated total',
    modConfirmAfterSlice: 'Estimate — Mod confirms after slicing',
    freeTotal: '0 VND — Free',
    ownMaterialFreeNote: 'Own material is not charged',
    printerSkipNote: 'Skip if unsure — a moderator will assign a suitable printer.',
    subSlotLabel: 'Preferred time within shift (recommended)',
    subSlotHint: 'Optional — a moderator will confirm the exact schedule.',
    noteLabel: 'Note',
    reviewFormLabel: 'Mode',
    reviewOwnFree: 'Own material — free',
    reviewTotal: 'Total',
    submitHint: 'Review your information before submitting to the queue.',
    editHint: 'You can go back to a previous step to make changes.',
    fileErrorGcode: 'Only .gcode and .gcode.3mf files are supported (pre-sliced from Bambu/Orca)',
    fileErrorStl: 'Only unsliced files (.stl, .3mf) are supported. Do not upload .gcode or .gcode.3mf in this mode',
    uploadFailed: 'Upload failed',
    submitFailed: 'Submit request failed',
    confirmTermsError: 'Please confirm the terms before submitting.',
  },
} as const;

function deepMerge<T extends Record<string, any>>(base: T, override: Record<string, any>): T {
  const result: Record<string, any> = Array.isArray(base) ? [...base] : { ...base };
  for (const [key, value] of Object.entries(override)) {
    const current = result[key];
    result[key] = value && typeof value === 'object' && !Array.isArray(value) && current && typeof current === 'object' && !Array.isArray(current)
      ? deepMerge(current, value)
      : value;
  }
  return result as T;
}

export const uiText = {
  VN: vnText,
  JP: deepMerge(vnText, jpOverrides),
} as const;

export const translations = {
  VN: {
    appName: 'BCSE 3D Lab',
    appSubtitle: 'VJU My Dinh · VJU Hoa Lac',
    labOnline: 'Lab đang hoạt động',
    welcome: 'Chào mừng trở lại',
    registerTitle: 'Đăng ký tài khoản',
    loginSubtitle: 'Đăng nhập để quản lý yêu cầu in 3D của bạn.',
    registerSubtitle: 'Tham gia không gian in 3D của VJU-BCSE Lab.',
    login: 'Đăng nhập',
    register: 'Đăng ký',
    registerNow: 'Đăng ký ngay',
    logout: 'Đăng xuất',
    email: 'Email',
    emailPlaceholder: 'name@st.vju.ac.vn',
    emailHint: 'Chỉ chấp nhận email @st.vju.ac.vn hoặc @vju.ac.vn',
    password: 'Mật khẩu',
    fullName: 'Họ và tên',
    studentId: 'Mã sinh viên',
    phone: 'Số điện thoại',
    supervisor: 'Giảng viên hướng dẫn (tùy chọn)',
    registerSuccess: 'Đăng ký thành công. Bạn có thể đăng nhập ngay bây giờ.',
    invalidEmail: 'Chỉ chấp nhận email VJU (@st.vju.ac.vn hoặc @vju.ac.vn)',
    dashboard: 'Tổng quan',
    booking: 'Tạo yêu cầu in',
    history: 'Lịch sử yêu cầu',
    queue: 'Hàng đợi duyệt',
    inventory: 'Vật tư',
    analytics: 'Bảng giá',
    users: 'Người dùng',
    printers: 'Máy in',
    chat: 'Trao đổi',
    backup: 'Sao lưu',
    settings: 'Thiết lập',
    pendingJobs: 'Yêu cầu đang chờ',
    totalJobs: 'Tổng số yêu cầu',
    printing: 'Đang in',
    done: 'Hoàn thành',
    myJobs: 'Yêu cầu của tôi',
    allJobs: 'Tất cả yêu cầu',
    noJobs: 'Chưa có yêu cầu nào',
    newRequest: 'Tạo yêu cầu mới',
    readyToPrint: 'Sẵn sàng in?',
    readyToPrintDesc: 'Tạo yêu cầu mới và bắt đầu dự án của bạn ngay hôm nay.',
    quickActions: 'Thao tác nhanh',
    statusTracking: 'Theo dõi trạng thái',
    labStats: 'Thống kê lab',
    viewAllHistory: 'Xem toàn bộ lịch sử',
    pendingApproval: 'Chờ duyệt',
    activeUsers: 'Người dùng hoạt động',
    step1: 'Hình thức',
    step2: 'Vật liệu',
    step3: 'File',
    step4: 'Máy & lịch',
    step5: 'Xác nhận',
    printMode: 'Hình thức in',
    selfPrint: 'Tự in',
    selfPrintDesc: 'Bạn tự vận hành máy tại lab.',
    labAssisted: 'In hộ',
    labAssistedDesc: 'Lab vận hành máy cho bạn.',
    slicedFileRequired: 'Yêu cầu file đã slice (.gcode hoặc .gcode.3mf)',
    slicedFileNote: 'Vui lòng slice model bằng Bambu Studio, Cura hoặc phần mềm tương đương trước khi tải lên.',
    labWillSlice: 'Lab sẽ tự slice file và báo giá trước khi in.',
    waitingQuote: 'Chờ duyệt và báo giá',
    waitingSchedule: 'Chờ xếp lịch',
    jobName: 'Tên yêu cầu in',
    jobNamePlaceholder: 'Ví dụ: Vỏ hộp Arduino',
    purpose: 'Mục đích sử dụng',
    purposePlaceholder: 'Mô tả ngắn gọn mục đích in của bạn',
    uploadFile: 'Tải file lên (STL/3MF)',
    uploadHint: 'Kéo thả hoặc nhấn để tải file lên',
    uploadNote: 'Hỗ trợ .stl, .3mf, tối đa 50MB',
    uploadSuccess: 'Tải file thành công',
    deleteFile: 'Xóa file',
    estimatedTime: 'Thời gian in ước tính',
    estimatedTimeHint: 'Lấy từ phần mềm slicer sau khi slice model.',
    hours: 'Giờ',
    minutes: 'Phút',
    estimatedGrams: 'Khối lượng nhựa ước tính',
    estimatedGramsHint: 'Lấy từ phần mềm slicer sau khi slice model.',
    selectPrinter: 'Chọn máy in',
    printerAvailable: 'Sẵn sàng',
    printerBusy: 'Đang bận',
    printerMaintenance: 'Bảo trì',
    printerAMS: 'AMS · Đa màu',
    queue_length: 'Hàng đợi',
    materialType: 'Loại nhựa',
    color: 'Màu',
    colorAMS: '(AMS - tối đa 4 màu)',
    colorSelected: 'Đã chọn',
    materialSource: 'Nguồn vật liệu',
    ownMaterial: 'Nhựa tự mang',
    ownMaterialDesc: 'Bạn tự cung cấp cuộn nhựa cho lab.',
    labMaterial: 'Mua nhựa từ lab',
    labMaterialDesc: 'Sử dụng nhựa có sẵn tại lab.',
    costEstimate: 'Ước tính chi phí',
    total: 'Tổng cộng',
    payLater: 'Thanh toán sau',
    freeMaterial: 'Miễn phí vật liệu',
    preferredDate: 'Ngày mong muốn',
    timeSlot: 'Khung giờ',
    timezone: 'Múi giờ: Asia/Bangkok (UTC+7)',
    scheduleNote: 'Khung giờ bạn chọn là mong muốn. Moderator sẽ chốt lịch dựa trên hàng đợi thực tế.',
    reviewRequest: 'Kiểm tra lại yêu cầu',
    reviewSubtitle: 'Vui lòng xác nhận các thông tin dưới đây là chính xác.',
    confirmCheckbox: 'Tôi xác nhận đã kiểm tra file in và tuân thủ quy định an toàn của lab.',
    submitRequest: 'Gửi yêu cầu',
    back: 'Quay lại',
    next: 'Tiếp tục',
    cancel: 'Hủy',
    notNamed: 'Chưa đặt tên',
    notSelected: 'Chưa chọn',
    notAssigned: 'Chưa xếp',
    waitingApproval: 'Chờ duyệt',
    area: 'Khu vực',
    attachment: 'Tệp đính kèm',
    printerName: 'Máy in',
    slicerFrom: 'Nguồn nhựa',
    statusDraft: 'Nháp',
    statusSubmitted: 'Đã gửi',
    statusPendingReview: 'Chờ duyệt',
    statusApproved: 'Đã duyệt',
    statusScheduled: 'Đã lên lịch',
    statusPrinting: 'Đang in',
    statusDone: 'Hoàn thành',
    statusRejected: 'Từ chối',
    statusCancelled: 'Đã hủy',
    heroTitle: 'Gửi yêu cầu in 3D',
    heroHighlight: 'nhanh và rõ ràng',
    heroDesc: 'Hệ thống quản lý yêu cầu in 3D dành cho sinh viên VJU.',
    featurePolicy: 'Quy trình rõ ràng',
    featurePolicyDesc: 'Mọi yêu cầu đều đi qua quy trình kiểm duyệt trước khi lên máy.',
    featureMaterial: 'Vật liệu linh hoạt',
    featureMaterialDesc: 'Tự mang nhựa hoặc dùng vật liệu có sẵn tại lab.',
    featureSafe: 'An toàn và kiểm soát',
    featureSafeDesc: 'Quản lý tài khoản, trạng thái máy in và lịch sử yêu cầu trong một hệ thống thống nhất.',
    userGuide: 'Hướng dẫn sử dụng',
    contactSupport: 'Liên hệ hỗ trợ',
    copyright: '© 2026 VJU-BCSE Lab',
    loading: 'Đang tải...',
    loadingData: 'Đang tải dữ liệu...',
    loadingPrinters: 'Đang tải máy in...',
    error: 'Lỗi',
    serverError: 'Không thể kết nối máy chủ. Vui lòng kiểm tra lại backend.',
    retry: 'Thử lại',
    save: 'Lưu',
    edit: 'Chỉnh sửa',
    delete: 'Xóa',
    confirm: 'Xác nhận',
    close: 'Đóng',
    search: 'Tìm kiếm',
    noData: 'Không có dữ liệu',
    morning: 'Sáng',
    afternoon: 'Chiều',
    evening: 'Tối',
    morning_range: '08:00 - 12:00',
    afternoon_range: '13:00 - 17:00',
    evening_range: '18:00 - 22:00',
    pricePerGram: 'đ/g',
    gram: 'gram',
    notSet: 'Chưa thiết lập',
  },
  EN: {
    appName: 'BCSE 3D Lab',
    appSubtitle: 'VJU My Dinh Â· VJU Hoa Lac',
    labOnline: 'Lab online',
    welcome: 'Welcome back',
    registerTitle: 'Create account',
    loginSubtitle: 'Sign in to manage your 3D print requests.',
    registerSubtitle: 'Join the 3D printing workspace of VJU-BCSE Lab.',
    login: 'Log in',
    register: 'Register',
    registerNow: 'Register now',
    logout: 'Log out',
    email: 'Email',
    emailPlaceholder: 'name@st.vju.ac.vn',
    emailHint: 'Only @st.vju.ac.vn or @vju.ac.vn emails are accepted',
    password: 'Password',
    fullName: 'Full name',
    studentId: 'Student ID',
    phone: 'Phone number',
    supervisor: 'Supervisor (optional)',
    registerSuccess: 'Registration successful. You can sign in now.',
    invalidEmail: 'Only VJU email addresses are accepted (@st.vju.ac.vn or @vju.ac.vn)',
    dashboard: 'Overview',
    booking: 'Create request',
    history: 'Request history',
    queue: 'Review queue',
    inventory: 'Materials',
    analytics: 'Pricing',
    users: 'Users',
    printers: 'Printers',
    chat: 'Messages',
    backup: 'Backups',
    settings: 'Settings',
    pendingJobs: 'Pending requests',
    totalJobs: 'Total requests',
    printing: 'Printing',
    done: 'Completed',
    myJobs: 'My requests',
    allJobs: 'All requests',
    noJobs: 'No requests yet',
    newRequest: 'New request',
    readyToPrint: 'Ready to print?',
    readyToPrintDesc: 'Create a new request and start your project today.',
    quickActions: 'Quick actions',
    statusTracking: 'Status tracking',
    labStats: 'Lab stats',
    viewAllHistory: 'View full history',
    pendingApproval: 'Pending approval',
    activeUsers: 'Active users',
    step1: 'Mode',
    step2: 'Material',
    step3: 'File',
    step4: 'Printer & time',
    step5: 'Confirm',
    printMode: 'Print mode',
    selfPrint: 'Self print',
    selfPrintDesc: 'You operate the printer at the lab.',
    labAssisted: 'Operator assist',
    labAssistedDesc: 'Lab staff operate the printer for you.',
    slicedFileRequired: 'A sliced file is required (.gcode or .gcode.3mf)',
    slicedFileNote: 'Please slice the model in Bambu Studio, Cura or an equivalent tool before upload.',
    labWillSlice: 'The lab will slice the file and confirm the quote before printing.',
    waitingQuote: 'Waiting for review and quote',
    waitingSchedule: 'Waiting for scheduling',
    jobName: 'Request name',
    jobNamePlaceholder: 'Example: Arduino enclosure',
    purpose: 'Purpose',
    purposePlaceholder: 'Briefly describe what this print is for',
    uploadFile: 'Upload file (STL/3MF)',
    uploadHint: 'Drag and drop or click to upload',
    uploadNote: 'Supports .stl, .3mf, max 50MB',
    uploadSuccess: 'Upload successful',
    deleteFile: 'Delete file',
    estimatedTime: 'Estimated print time',
    estimatedTimeHint: 'Take this from your slicer after slicing the model.',
    hours: 'Hours',
    minutes: 'Minutes',
    estimatedGrams: 'Estimated material usage',
    estimatedGramsHint: 'Take this from your slicer after slicing the model.',
    selectPrinter: 'Choose a printer',
    printerAvailable: 'Available',
    printerBusy: 'Busy',
    printerMaintenance: 'Maintenance',
    printerAMS: 'AMS Â· Multi-color',
    queue_length: 'Queue',
    materialType: 'Material type',
    color: 'Color',
    colorAMS: '(AMS - up to 4 colors)',
    colorSelected: 'Selected',
    materialSource: 'Material source',
    ownMaterial: 'Bring your own filament',
    ownMaterialDesc: 'You provide the filament reel.',
    labMaterial: 'Use lab material',
    labMaterialDesc: 'Use material currently stocked by the lab.',
    costEstimate: 'Estimated cost',
    total: 'Total',
    payLater: 'Pay later',
    freeMaterial: 'Free material',
    preferredDate: 'Preferred date',
    timeSlot: 'Time slot',
    timezone: 'Timezone: Asia/Bangkok (UTC+7)',
    scheduleNote: 'Your selected slot is a preference. A moderator will confirm the final schedule based on queue load.',
    reviewRequest: 'Review your request',
    reviewSubtitle: 'Please confirm the information below is correct.',
    confirmCheckbox: 'I confirm that I checked the file and will follow the lab safety rules.',
    submitRequest: 'Submit request',
    back: 'Back',
    next: 'Next',
    cancel: 'Cancel',
    notNamed: 'Unnamed',
    notSelected: 'Not selected',
    notAssigned: 'Unassigned',
    waitingApproval: 'Pending review',
    area: 'Area',
    attachment: 'Attachment',
    printerName: 'Printer',
    slicerFrom: 'Material source',
    statusDraft: 'Draft',
    statusSubmitted: 'Submitted',
    statusPendingReview: 'Pending review',
    statusApproved: 'Approved',
    statusScheduled: 'Scheduled',
    statusPrinting: 'Printing',
    statusDone: 'Completed',
    statusRejected: 'Rejected',
    statusCancelled: 'Cancelled',
    heroTitle: 'Submit a 3D print request',
    heroHighlight: 'quickly and clearly',
    heroDesc: 'A 3D print request workspace for students and lab operators at VJU-BCSE.',
    featurePolicy: 'Clear workflow',
    featurePolicyDesc: 'Every request goes through review before it reaches a printer.',
    featureMaterial: 'Flexible materials',
    featureMaterialDesc: 'Bring your own filament or use material stocked by the lab.',
    featureSafe: 'Controlled and safe',
    featureSafeDesc: 'Accounts, printer state and request history stay under one system.',
    userGuide: 'User guide',
    contactSupport: 'Contact support',
    copyright: 'Â© 2026 VJU-BCSE Lab',
    loading: 'Loading...',
    loadingData: 'Loading data...',
    loadingPrinters: 'Loading printers...',
    error: 'Error',
    serverError: 'Unable to connect to the server. Please check the backend.',
    retry: 'Retry',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    confirm: 'Confirm',
    close: 'Close',
    search: 'Search',
    noData: 'No data',
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
    morning_range: '08:00 - 12:00',
    afternoon_range: '13:00 - 17:00',
    evening_range: '18:00 - 22:00',
    pricePerGram: 'VND/g',
    gram: 'g',
    notSet: 'Not set',
  },
} as const;


export type TranslationKey = keyof typeof translations.VN;
export type UiText = typeof uiText.VN;
export type UiLang = Lang;

export function getUiText(lang: Lang) {
  return uiText[lang] ?? uiText.VN;
}

export function fillText(template: string, params?: Record<string, string | number>) {
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_, key) => String(params[key] ?? ''));
}

