import { JobStatus, MaterialType, Printer, PrintJob, Role, MaterialSource } from './types';

export const MOCK_PRINTERS: Printer[] = [
  {
    id: 'p1',
    name: 'Prusa i3 MK3S+ #1',
    buildVolume: '250 x 210 x 210 mm',
    supportedMaterials: [MaterialType.PLA, MaterialType.PETG],
    status: 'Available',
    queueLength: 0,
  },
  {
    id: 'p2',
    name: 'Prusa i3 MK3S+ #2',
    buildVolume: '250 x 210 x 210 mm',
    supportedMaterials: [MaterialType.PLA, MaterialType.PETG],
    status: 'Busy',
    queueLength: 2,
    nextAvailable: '2026-02-23T09:00:00',
  },
  {
    id: 'p3',
    name: 'Ender 3 V2',
    buildVolume: '220 x 220 x 250 mm',
    supportedMaterials: [MaterialType.PLA],
    status: 'Maintenance',
    queueLength: 0,
  },
];

export const MOCK_JOBS: PrintJob[] = [
  {
    id: 'JOB-001',
    userId: 'u1',
    userName: 'Nguyễn Văn A',
    jobName: 'Vỏ hộp Arduino',
    fileName: 'arduino_case.stl',
    estimatedTime: '2h 15m',
    estimatedGrams: 45,
    materialType: MaterialType.PLA,
    color: 'Xanh dương',
    materialSource: MaterialSource.LAB,
    status: JobStatus.DONE,
    cost: 45000,
    createdAt: '2026-02-20T10:00:00',
    actualGrams: 48,
    printerName: 'Prusa i3 MK3S+ #1',
    slotTime: '2026-02-21 08:00 - 10:15',
  },
  {
    id: 'JOB-002',
    userId: 'u1',
    userName: 'Nguyễn Văn A',
    jobName: 'Bánh răng robot',
    fileName: 'gear_v2.3mf',
    estimatedTime: '1h 45m',
    estimatedGrams: 30,
    materialType: MaterialType.PETG,
    color: 'Đen',
    materialSource: MaterialSource.OWN,
    status: JobStatus.PENDING_REVIEW,
    cost: 0,
    createdAt: '2026-02-22T14:30:00',
  },
  {
    id: 'JOB-003',
    userId: 'u2',
    userName: 'Trần Thị B',
    jobName: 'Mô hình kiến trúc',
    fileName: 'building_model.stl',
    estimatedTime: '12h 00m',
    estimatedGrams: 250,
    materialType: MaterialType.PLA,
    color: 'Trắng',
    materialSource: MaterialSource.LAB,
    status: JobStatus.PRINTING,
    cost: 250000,
    createdAt: '2026-02-22T08:00:00',
    printerName: 'Prusa i3 MK3S+ #2',
    slotTime: '2026-02-22 08:00 - 20:00',
  },
];

export const PRICING_RULES = [
  { material: MaterialType.PLA, pricePerGram: 1000 },
  { material: MaterialType.PETG, pricePerGram: 1200 },
];

export const STATUS_COLORS: Record<JobStatus, string> = {
  [JobStatus.DRAFT]: 'bg-gray-100 text-gray-600 border-gray-200',
  [JobStatus.SUBMITTED]: 'bg-blue-50 text-blue-600 border-blue-200',
  [JobStatus.PENDING_REVIEW]: 'bg-amber-50 text-amber-600 border-amber-200',
  [JobStatus.APPROVED]: 'bg-indigo-50 text-indigo-600 border-indigo-200',
  [JobStatus.SCHEDULED]: 'bg-sky-50 text-sky-600 border-sky-200',
  [JobStatus.PRINTING]: 'bg-emerald-50 text-emerald-600 border-emerald-200 animate-pulse',
  [JobStatus.DONE]: 'bg-green-50 text-green-600 border-green-200',
  [JobStatus.REJECTED]: 'bg-red-50 text-red-600 border-red-200',
  [JobStatus.CANCELLED]: 'bg-gray-50 text-gray-400 border-gray-200',
  [JobStatus.NEEDS_REVISION]: 'bg-orange-50 text-orange-600 border-orange-200',
};
